// Built-in naming / design standards for an initialized electrical install.
//
// The `electrical_naming_standards` table is the display source, but the
// Standards page must never render blank on a freshly initialized environment,
// so these canonical entries are used as a fallback and to fill gaps by key.
// They document convention only — they never change stable IDs or records.

import {
  INFRASTRUCTURE_ID_STANDARDS,
  type InfrastructureKind,
} from "./electrical-infrastructure-standards";

export interface StandardEntry {
  key: string;
  title: string;
  body: string;
  sort_order: number;
}

export const BUILT_IN_STANDARDS: readonly StandardEntry[] = [
  {
    key: "id_formats",
    title: "Entity ID formats",
    body:
      "Farm Shop load FS-### (FS-097). Pump House load PH-### (PH-028, legacy suffixes PH-019a/PH-019b). " +
      "Boiler load BL-### (BL-004). House load HSE-## . Panel PNL-<building>-<role> (PNL-FS-CRIT). " +
      "Raceway CON-### (CON-105) for every raceway type — construction (EMT, FLEX/FMC/LFMC, PVC, " +
      "underground, sleeve) is the separate Raceway type field and is never encoded into the ID. " +
      "Junction box JB-###-## (JB-104-01). Branch raceway BR-###-##-## (BR-104-02-03). " +
      "Stable IDs are permanent: they are never renamed or renumbered, and they carry no physical attributes.",
    sort_order: 10,
  },
  {
    key: "hierarchical_ids",
    title: "Hierarchical raceway / junction box / branch convention",
    body:
      "A field technician must be able to read the originating raceway and junction box directly from the ID.\n" +
      "CON-### — the three digits are the unique raceway path ID and become the root inherited downstream.\n" +
      "JB-###-## — parent raceway path, then the sequential junction box number along that path.\n" +
      "BR-###-##-## — raceway path, the junction box the branch physically originates from, then the branch sequence.\n" +
      "BR-104-02-03 reads as branch 03 originating from junction box 02 on raceway path 104.\n" +
      "Branch numbering restarts at 01 for each junction box; each box keeps its own branch sequence.",
    sort_order: 12,
  },
  {
    key: "branch_origin",
    title: "Branch origin rule",
    body:
      "A branch MUST inherit the identifier of the junction box it physically originates from — never number " +
      "branches against the root raceway alone, because that loses the junction box relationship.\n" +
      "Correct: CON-104 > JB-104-01 > JB-104-02 > BR-104-02-01 … BR-104-02-04.\n" +
      "Incorrect: BR-104-01, BR-104-02, BR-104-03, BR-104-04.",
    sort_order: 14,
  },
  {
    key: "id_validation",
    title: "ID validation and parent agreement",
    body:
      "The same rules validate the Standards page, record create/edit forms and Source of Record checks.\n" +
      "Raceway ^CON-\\d{3}$ (valid CON-104; invalid CON-NE-001, CON-104-01).\n" +
      "Junction box ^JB-\\d{3}-\\d{2}$ (valid JB-104-01; invalid JB-104, JB-104-1).\n" +
      "Branch ^BR-\\d{3}-\\d{2}-\\d{2}$ (valid BR-104-02-01; invalid BR-104-01, BR-104-2-1).\n" +
      "Where relationship data exists, the encoded parent must match the linked parent record: BR-104-02-03 " +
      "linked to JB-104-03 is flagged as invalid in the QA report. IDs are generated by the application " +
      "(next junction box along a path, next branch from a box) so they are not hand-constructed.\n" +
      "Records created before this convention keep their IDs and are reported as legacy, never renamed.",
    sort_order: 16,
  },
  {
    key: "raceway_continuity",
    title: "Continuous raceway rule",
    body:
      "A CON-### is one continuous physical raceway between actual accessible endpoints (panel, junction box, " +
      "handhole, or equipment). Changing size, type, status, or measured length never splits or renames a raceway.",
    sort_order: 20,
  },
  {
    key: "waypoints",
    title: "Waypoint vs endpoint",
    body:
      "Bends, sweeps, trench direction changes, and geographic route changes with no physically installed, " +
      "accessible box are route waypoints on the raceway. Only real planned or installed accessible junction " +
      "boxes receive a JB-###-## record.",
    sort_order: 30,
  },

  {
    key: "environments",
    title: "Interior and site raceways",
    body:
      "Interior and exterior raceways share one canonical raceway dataset. The environment field " +
      "(INTERIOR, SITE_UNDERGROUND, SITE_EXPOSED) separates them — never duplicate records per environment.",
    sort_order: 40,
  },
  {
    key: "panel_exit",
    title: "Panel raceway physical exit convention",
    body:
      "Standing in front of and facing a panel, physical raceway exit assignment starts at the lower-right " +
      "corner and proceeds counterclockwise. Exit order and exit side are physical position only: changing an " +
      "exit position never renames a Conduit ID.",
    sort_order: 50,
  },
  {
    key: "farm_shop_walk",
    title: "Farm Shop installation walk",
    body:
      "A6 is the northeast (NE) corner. The perimeter walk begins at A6 and travels clockwise, outside-in; " +
      "inner rectangles follow the same convention. The walk order is an installation sequence only and never " +
      "changes stable Load IDs.",
    sort_order: 60,
  },
  {
    key: "circuit_groups",
    title: "Circuit group derivation",
    body:
      "Circuit groups are engineering values owned by the canonical workbook and are derived from the " +
      "Load_Master circuit group ID and description columns — there is no separate Circuit Groups worksheet. " +
      "A group is created once and shared by every load that references it; loads with no resolvable group " +
      "are reported, never guessed.",
    sort_order: 65,
  },
  {
    key: "breaker_positions",
    title: "Breaker position convention",
    body:
      "Circuit assignment records both the electrical breaker/circuit number and the field-visible physical " +
      "position (Left/Right plus index). Two circuit groups may not share one breaker number in the same panel.",
    sort_order: 70,
  },
  {
    key: "labels",
    title: "Label conventions",
    body:
      "Five label classes: load/device/circuit, panel/breaker, raceway/conduit, junction box, and branch run. " +
      "Label state tracks queued, printed, and installed, with an explicit reprint flag when the record changes " +
      "after printing.",
    sort_order: 80,
  },
  {
    key: "infrastructure_ids",
    title: "Infrastructure ID formats — racks, power assets, network and powered devices",
    body:
      "Equipment rack RACK-<SITE>-<ROLE>-## (RACK-FS-NET-01, RACK-FS-HAM-01, RACK-PH-NET-01).\n" +
      "Power distribution asset PWR-<TYPE>-<SITE>-<ROLE>-## (PWR-PDU-FS-NET-01, PWR-PSU-FS-HAM-01, PWR-UPS-FS-NET-01); " +
      "TYPE is PDU, PSU, UPS, CONV or CHG and is a readability aid — the typed Asset type field stays authoritative.\n" +
      "Network device NET-<TYPE>-<SITE>-## (NET-SW-FS-01, NET-SW-PH-01); TYPE is SW, RTR, AP, FW, BR or ONT.\n" +
      "Powered device DEV-<CLASS>-<ROLE>-<SITE>-## (DEV-HAM-RADIO-FS-01, DEV-NET-SERVER-FS-01, DEV-NET-NVR-FS-01).\n" +
      "SITE is a controlled location code (FS, PH, BLR, HSE, SITE) and ROLE a controlled infrastructure class (NET, HAM, SERVER, AV, CONTROL, SEC).\n" +
      "The infrastructure ID names the operational role, never the hardware: replacing the physical switch, rack or power " +
      "supply keeps NET-SW-PH-01, RACK-FS-NET-01 and PWR-PSU-FS-HAM-01 and rebuilds no topology.\n" +
      "Create a powered-device record only when its power dependency or topology matters operationally — ordinary " +
      "inventory items do not need an infrastructure record.",
    sort_order: 92,
  },
  {
    key: "infrastructure_power_topology",
    title: "Immediate versus upstream power source",
    body:
      "Every power asset and device preserves BOTH its immediate power source and its upstream electrical source, so " +
      "failure domains stay computable:\n" +
      "PNL-FS-NET → receptacle / circuit → UPS or PDU → switch.\n" +
      "PNL-FS-NW → 30A branch circuit → PWR-PSU-FS-HAM-01 → DEV-HAM-RADIO-FS-01.\n" +
      "A rack is not an electrical panel, and a shared DC power supply is not a panel merely because it distributes " +
      "power. The ham rack is ordinary reusable infrastructure topology (RACK-FS-HAM-01 containing " +
      "PWR-PSU-FS-HAM-01 plus radio device roles), never a special-case schema.",
    sort_order: 94,
  },
  {
    key: "infrastructure_asset_linkage",
    title: "Infrastructure vs Inventory Asset ownership",
    body:
      "Racks, power assets and devices expose both \"link an existing FarmOps Asset\" and \"create an Asset and link\". " +
      "Infrastructure owns the stable ID, role and topology. The linked Inventory Asset remains authoritative for " +
      "manufacturer, model, serial number, warranty, maintenance and replacement history — never duplicate those " +
      "lifecycle fields on the infrastructure record.",
    sort_order: 96,
  },
  {
    key: "authority",
    title: "Authority boundary",
    body:
      "The canonical ODS remains the engineering release authority for voltage, amperage, demand, circuit " +
      "grouping, and engineering assignment. FarmOps owns raceways, junction boxes, branch runs, measured / " +
      "as-built lengths, install status, labels, physical exits, and field notes.",
    sort_order: 90,
  },
];

/**
 * Stable-ID reference table. This ships with the application rather than
 * depending on a data seed, so a fresh or existing installation always renders
 * the reference rows with no manual entry and no duplication risk.
 */
export interface StableIdReferenceRow {
  entity: string;
  format: string;
  example: string;
  notes: string;
}

export const STABLE_ID_REFERENCE: readonly StableIdReferenceRow[] = [
  {
    entity: "Farm Shop Load",
    format: "FS-###",
    example: "FS-097",
    notes: "Stable load ID",
  },
  {
    entity: "Pump House Load",
    format: "PH-###",
    example: "PH-028",
    notes: "Stable load ID (legacy split suffixes PH-019a / PH-019b are permitted)",
  },
  {
    entity: "Boiler Load",
    format: "BL-###",
    example: "BL-003",
    notes: "Stable load ID",
  },
  {
    entity: "House Load",
    format: "HSE-##",
    example: "HSE-12",
    notes: "Stable load ID — House convention is explicit, never a catch-all",
  },
  {
    entity: "Panel",
    format: "PNL-*",
    example: "PNL-FS-NE",
    notes: "Stable panel ID",
  },
  {
    entity: "Raceway (all types)",
    format: "CON-###",
    example: "CON-105",
    notes:
      "Canonical raceway ID for EMT, FLEX/FMC/LFMC, PVC, underground and sleeves alike. " +
      "Encodes the raceway / path ID; root identifier inherited downstream. Construction is the " +
      "separate Raceway type field and is never part of the ID.",
  },
  {
    entity: "Junction Box",
    format: "JB-###-##",
    example: "JB-104-02",
    notes: "Encodes raceway path + junction box sequence; actual accessible box only",
  },
  {
    entity: "Branch Raceway",
    format: "BR-###-##-##",
    example: "BR-104-02-03",
    notes: "Encodes raceway path + origin junction box + branch sequence (resets per box)",
  },

];

/** Infrastructure reference rows, derived from the centralized standards. */
export const INFRASTRUCTURE_ID_REFERENCE: readonly StableIdReferenceRow[] = (
  ["rack", "power_asset", "device"] as InfrastructureKind[]
).flatMap((kind) => {
  const std = INFRASTRUCTURE_ID_STANDARDS[kind];
  return std.formats.map((format) => ({
    entity: format.name,
    format: format.shape,
    example: format.examples[0],
    notes: std.stabilityNote,
  }));
});

/** Merge database rows with the built-in set, preferring stored rows by key. */
export function mergeStandards(rows: Record<string, unknown>[]): StandardEntry[] {
  const merged = new Map<string, StandardEntry>();
  for (const entry of BUILT_IN_STANDARDS) merged.set(entry.key, entry);
  for (const row of rows) {
    const key = String(row["key"] ?? "").trim();
    const title = String(row["title"] ?? "").trim();
    const body = String(row["body"] ?? "").trim();
    if (!key || !title || !body) continue;
    merged.set(key, {
      key,
      title,
      body,
      sort_order: Number(row["sort_order"] ?? merged.get(key)?.sort_order ?? 999) || 999,
    });
  }
  return [...merged.values()].sort(
    (a, b) => a.sort_order - b.sort_order || a.key.localeCompare(b.key),
  );
}
