// Built-in naming / design standards for an initialized electrical install.
//
// The `electrical_naming_standards` table is the display source, but the
// Standards page must never render blank on a freshly initialized environment,
// so these canonical entries are used as a fallback and to fill gaps by key.
// They document convention only — they never change stable IDs or records.

import {
  INFRASTRUCTURE_ID_STANDARDS,
  type InfrastructureKind,
} from "./electrical-infrastructure-standards";
import {
  BREAKER_REFERENCE_EXAMPLE,
  BREAKER_REFERENCE_SHAPE,
  CIRCUIT_GROUP_ID_EXAMPLE,
  CIRCUIT_GROUP_ID_SHAPE,
} from "./electrical-breaker-reference";


export interface StandardEntry {
  key: string;
  title: string;
  body: string;
  sort_order: number;
}

const INFRA_KINDS: readonly InfrastructureKind[] = ["rack", "power_asset", "device"];

/**
 * Render the infrastructure naming standard straight out of the shared module:
 * shapes, examples, token meanings and controlled vocabularies all come from
 * `INFRASTRUCTURE_ID_STANDARDS`, never from prose duplicated here.
 */
export function infrastructureIdStandardsBody(): string {
  const lines: string[] = [];
  for (const kind of INFRA_KINDS) {
    const std = INFRASTRUCTURE_ID_STANDARDS[kind];
    for (const format of std.formats) {
      lines.push(`${format.name} ${format.shape} (${format.examples.join(", ")}).`);
      for (const token of format.tokens) {
        if (!token.token.startsWith("<")) continue;
        lines.push(`  ${token.token} — ${token.meaning}.`);
      }
    }
    lines.push(`  ${std.stabilityNote}`);
    for (const legacy of std.legacyFormats ?? []) {
      lines.push(
        `  Legacy ${legacy.shape} remains valid on records that already exist and is refused for new records.`,
      );
    }
  }
  return lines.join("\n");
}

export const BUILT_IN_STANDARDS: readonly StandardEntry[] = [
  {
    key: "id_formats",
    title: "Entity ID formats",
    body:
      "Farm Shop load FS-### (FS-097). Pump House load PH-### (PH-028, legacy suffixes PH-019a/PH-019b). " +
      "Boiler load BL-### (BL-004). House load HSE-## . Panel PNL-<building>-<role> (PNL-FS-CRIT). " +
      "Raceway CON-### (CON-105) for every raceway type — construction (EMT, FLEX/FMC/LFMC, PVC, " +
      "underground, sleeve) is the separate Raceway type field and is never encoded into the ID. " +
      "Junction box JB-###-## (JB-104-01). Branch raceway BR-###-##-## (BR-104-02-03). " +
      "Stable IDs are permanent: they are never renamed or renumbered, and they carry no physical attributes.",
    sort_order: 10,
  },
  {
    key: "hierarchical_ids",
    title: "Hierarchical raceway / junction box / branch convention",
    body:
      "A field technician must be able to read the originating raceway and junction box directly from the ID.\n" +
      "CON-### — the three digits are the unique raceway path ID and become the root inherited downstream.\n" +
      "JB-###-## — parent raceway path, then the sequential junction box number along that path.\n" +
      "BR-###-##-## — raceway path, the junction box the branch physically originates from, then the branch sequence.\n" +
      "BR-104-02-03 reads as branch 03 originating from junction box 02 on raceway path 104.\n" +
      "Branch numbering restarts at 01 for each junction box; each box keeps its own branch sequence.",
    sort_order: 12,
  },
  {
    key: "branch_origin",
    title: "Branch origin rule",
    body:
      "A branch MUST inherit the identifier of the junction box it physically originates from — never number " +
      "branches against the root raceway alone, because that loses the junction box relationship.\n" +
      "Correct: CON-104 > JB-104-01 > JB-104-02 > BR-104-02-01 … BR-104-02-04.\n" +
      "Incorrect: BR-104-01, BR-104-02, BR-104-03, BR-104-04.",
    sort_order: 14,
  },
  {
    key: "id_validation",
    title: "ID validation and parent agreement",
    body:
      "The same rules validate the Standards page, record create/edit forms and Source of Record checks.\n" +
      "Raceway ^CON-\\d{3}$ (valid CON-104; invalid CON-NE-001, CON-104-01).\n" +
      "Junction box ^JB-\\d{3}-\\d{2}$ (valid JB-104-01; invalid JB-104, JB-104-1).\n" +
      "Branch ^BR-\\d{3}-\\d{2}-\\d{2}$ (valid BR-104-02-01; invalid BR-104-01, BR-104-2-1).\n" +
      "Where relationship data exists, the encoded parent must match the linked parent record: BR-104-02-03 " +
      "linked to JB-104-03 is flagged as invalid in the QA report. IDs are generated by the application " +
      "(next junction box along a path, next branch from a box) so they are not hand-constructed.\n" +
      "Records created before this convention keep their IDs and are reported as legacy, never renamed.",
    sort_order: 16,
  },
  {
    key: "raceway_continuity",
    title: "Continuous raceway rule",
    body:
      "A CON-### is one continuous physical raceway between actual accessible endpoints (panel, junction box, " +
      "handhole, or equipment). Changing size, type, status, or measured length never splits or renames a raceway.",
    sort_order: 20,
  },
  {
    key: "ordered_junction_points",
    title: "Ordered junction points along one raceway",
    body:
      "One continuous raceway can pass through several junction boxes in physical order. Each box records the " +
      "parent raceway plus its position along it (CON-104 > position 1 JB-104-01 > position 2 JB-104-02 > " +
      "position 3 JB-104-03). That link and position are the authoritative topology; the encoded ID only " +
      "cross-checks it. Never create an artificial raceway between two boxes on the same run, and a branch " +
      "leaving an intermediate box (BR-104-02-01) does not terminate the raceway. Branch runs keep their " +
      "immediate junction-box source — no redundant panel source is recorded. QA reports duplicate, missing, " +
      "or invalid positions and any identity disagreement; it never renames a record.",
    sort_order: 22,
  },
  {
    key: "waypoints",
    title: "Waypoint vs endpoint",
    body:
      "Bends, sweeps, trench direction changes, and geographic route changes with no physically installed, " +
      "accessible box are route waypoints on the raceway. Only real planned or installed accessible junction " +
      "boxes receive a JB-###-## record.",
    sort_order: 30,
  },

  {
    key: "environments",
    title: "Interior and site raceways",
    body:
      "Interior and exterior raceways share one canonical raceway dataset. The environment field " +
      "(INTERIOR, SITE_UNDERGROUND, SITE_EXPOSED) separates them — never duplicate records per environment.",
    sort_order: 40,
  },
  {
    key: "panel_exit",
    title: "Panel raceway physical exit convention",
    body:
      "Standing in front of and facing a panel, physical raceway exit assignment starts at the lower-right " +
      "corner and proceeds counterclockwise. Exit order and exit side are physical position only: changing an " +
      "exit position never renames a Conduit ID.",
    sort_order: 50,
  },
  {
    key: "farm_shop_walk",
    title: "Farm Shop installation walk",
    body:
      "A6 is the northeast (NE) corner. The perimeter walk begins at A6 and travels clockwise, outside-in; " +
      "inner rectangles follow the same convention. The walk order is an installation sequence only and never " +
      "changes stable Load IDs.",
    sort_order: 60,
  },
  {
    key: "circuit_groups",
    title: "Circuit group derivation",
    body:
      "Circuit groups are engineering values owned by the canonical workbook and are derived from the " +
      "Load_Master circuit group ID and description columns — there is no separate Circuit Groups worksheet. " +
      "A group is created once and shared by every load that references it; loads with no resolvable group " +
      "are reported, never guessed.",
    sort_order: 65,
  },
  {
    key: "breaker_positions",
    title: "Breaker position convention",
    body:
      "Circuit assignment records both the electrical breaker/circuit number and the field-visible physical " +
      "position (Left/Right plus index). Two circuit groups may not share one breaker number in the same panel.",
    sort_order: 70,
  },
  {
    key: "breaker_reference",
    title: "Derived breaker reference and circuit group relationship",
    body:
      `Breaker reference ${BREAKER_REFERENCE_SHAPE} (${BREAKER_REFERENCE_EXAMPLE}) is derived and read-only — ` +
      "it is a display projection, never an identity and never editable.\n" +
      "The authoritative breaker-position identity remains the panel UUID plus the physical position row in " +
      "electrical_breaker_positions.\n" +
      `Circuit groups keep independent permanent IDs ${CIRCUIT_GROUP_ID_SHAPE} (${CIRCUIT_GROUP_ID_EXAMPLE}).\n` +
      "Relationships are displayed as breaker_reference → circuit_group_id [description], for example " +
      `${BREAKER_REFERENCE_EXAMPLE} → ${CIRCUIT_GROUP_ID_EXAMPLE} [Shop east receptacles].\n` +
      "The relationship is stored only in electrical_breaker_positions.circuit_group_uuid.\n" +
      "Never concatenate a breaker reference into a circuit group stable ID, and never rename a circuit group " +
      "when its breaker assignment changes — reassignment changes the link, not the identity.",
    sort_order: 72,
  },

  {
    key: "labels",
    title: "Label conventions",
    body:
      "Five label classes: load/device/circuit, panel/breaker, raceway/conduit, junction box, and branch run. " +
      "Label state tracks queued, printed, and installed, with an explicit reprint flag when the record changes " +
      "after printing.",
    sort_order: 80,
  },
  {
    key: "infrastructure_ids",
    title: "Infrastructure ID formats — racks, power assets, network and powered devices",
    // Generated from INFRASTRUCTURE_ID_STANDARDS so the Standards page can never
    // drift from the vocabulary the validator and ID generators actually enforce.
    body: infrastructureIdStandardsBody(),
    sort_order: 92,
  },
  {
    key: "infrastructure_power_topology",
    title: "Immediate versus upstream power source",
    body:
      "Every power asset and device preserves BOTH its immediate power source and its upstream electrical source, so " +
      "failure domains stay computable:\n" +
      "PNL-FS-NET → receptacle / circuit → UPS or PDU → switch.\n" +
      "PNL-FS-NW → 30A branch circuit → PWR-PSU-FS-HAM-01 → DEV-HAM-RADIO-FS-01.\n" +
      "A rack is not an electrical panel, and a shared DC power supply is not a panel merely because it distributes " +
      "power. The ham rack is ordinary reusable infrastructure topology (RACK-FS-HAM-01 containing " +
      "PWR-PSU-FS-HAM-01 plus radio device roles), never a special-case schema.",
    sort_order: 94,
  },
  {
    key: "infrastructure_asset_linkage",
    title: "Infrastructure vs Inventory Asset ownership",
    body:
      "Racks, power assets and devices expose both \"link an existing FarmOps Asset\" and \"create an Asset and link\". " +
      "Infrastructure owns the stable ID, role and topology. The linked Inventory Asset remains authoritative for " +
      "manufacturer, model, serial number, warranty, maintenance and replacement history — never duplicate those " +
      "lifecycle fields on the infrastructure record.",
    sort_order: 96,
  },
  {
    key: "lifecycle_dimensions",
    title: "Lifecycle milestones and panel completeness",
    body:
      "One status can never describe design, procurement, installation, energization and verification at once. " +
      "Each object tracks these milestones separately, and any of them may be marked not applicable " +
      "(a direct-buried cable needs no raceway): Planned; Material ready; Breaker/device installed; " +
      "Raceway or cable pathway installed; Conductors pulled; Panel/source termination complete; " +
      "Load termination complete; Tested; Energized; As-built verified; Out of service; Retired/removed.\n" +
      "Material ready means the materials are physically on hand — it does not mean installation has begun.\n" +
      "Testing, energization and as-built verification only advance on explicit accepted evidence.\n" +
      "A panel reports separate results, never one combined bar: infrastructure stage; capacity utilization; " +
      "position documentation coverage; circuit rollout; and per-milestone counts (breakers installed, " +
      "circuit groups assigned, raceways, conductor pulls, terminations, tests, energization, loads, " +
      "as-built verification), with holds and conflicts listed separately.\n" +
      "Capacity utilization = occupied physical positions (poles) / usable physical positions. It is NOT project " +
      "completion: a 40-position panel with seven installed circuits is 17.5% utilized and can still be 100% " +
      "complete for a declared seven-circuit scope.\n" +
      "Circuit rollout = completed applicable milestones / total applicable milestones for declared in-scope " +
      "circuits. Not-applicable milestones leave the denominator entirely.\n" +
      "Every physical position is classified Active, Planned, Reserved, Spare or Unavailable. Spare and reserved " +
      "positions never reduce installation completion; only unclassified positions reduce documentation coverage. " +
      "A multi-pole breaker consumes several poles but counts as one breaker and normally one circuit group.\n" +
      "Panel percentages are always derived from breaker positions, circuit groups, branch runs, raceways, " +
      "terminations, loads, tests and accepted field observations — never stored as authoritative data, and cached " +
      "only for performance with a recalculate action. \"Panel complete\" means the declared scope is complete, " +
      "not that every position is occupied.",
    sort_order: 235,
  },
  {
    key: "authority",
    title: "Authority boundary",
    body:
      "The canonical ODS remains the engineering release authority for voltage, amperage, demand, circuit " +
      "grouping, and engineering assignment. FarmOps owns raceways, junction boxes, branch runs, measured / " +
      "as-built lengths, install status, labels, physical exits, and field notes.",
    sort_order: 90,
  },
];

/**
 * Stable-ID reference table. This ships with the application rather than
 * depending on a data seed, so a fresh or existing installation always renders
 * the reference rows with no manual entry and no duplication risk.
 */
export interface StableIdReferenceRow {
  entity: string;
  format: string;
  example: string;
  notes: string;
}

export const STABLE_ID_REFERENCE: readonly StableIdReferenceRow[] = [
  {
    entity: "Farm Shop Load",
    format: "FS-###",
    example: "FS-097",
    notes: "Stable load ID",
  },
  {
    entity: "Pump House Load",
    format: "PH-###",
    example: "PH-028",
    notes: "Stable load ID (legacy split suffixes PH-019a / PH-019b are permitted)",
  },
  {
    entity: "Boiler Load",
    format: "BL-###",
    example: "BL-003",
    notes: "Stable load ID",
  },
  {
    entity: "House Load",
    format: "HSE-##",
    example: "HSE-12",
    notes: "Stable load ID — House convention is explicit, never a catch-all",
  },
  {
    entity: "Panel",
    format: "PNL-*",
    example: "PNL-FS-NE",
    notes: "Stable panel ID",
  },
  {
    entity: "Raceway (all types)",
    format: "CON-###",
    example: "CON-105",
    notes:
      "Canonical raceway ID for EMT, FLEX/FMC/LFMC, PVC, underground and sleeves alike. " +
      "Encodes the raceway / path ID; root identifier inherited downstream. Construction is the " +
      "separate Raceway type field and is never part of the ID.",
  },
  {
    entity: "Junction Box",
    format: "JB-###-##",
    example: "JB-104-02",
    notes: "Encodes raceway path + junction box sequence; actual accessible box only",
  },
  {
    entity: "Branch Raceway",
    format: "BR-###-##-##",
    example: "BR-104-02-03",
    notes: "Encodes raceway path + origin junction box + branch sequence (resets per box)",
  },
  {
    entity: "Circuit Group",
    format: CIRCUIT_GROUP_ID_SHAPE,
    example: CIRCUIT_GROUP_ID_EXAMPLE,
    notes:
      "Permanent, independent of any breaker assignment. Never renamed when the breaker changes and " +
      "never has a breaker reference concatenated into it.",
  },
  {
    entity: "Breaker reference (derived, read-only)",
    format: BREAKER_REFERENCE_SHAPE,
    example: BREAKER_REFERENCE_EXAMPLE,
    notes:
      "Display projection only. Authoritative identity is the panel UUID plus physical position; the " +
      "circuit-group link is stored in electrical_breaker_positions.circuit_group_uuid.",
  },
];


/** Infrastructure reference rows, derived from the centralized standards. */
export const INFRASTRUCTURE_ID_REFERENCE: readonly StableIdReferenceRow[] = (
  ["rack", "power_asset", "device"] as InfrastructureKind[]
).flatMap((kind) => {
  const std = INFRASTRUCTURE_ID_STANDARDS[kind];
  return std.formats.map((format) => ({
    entity: format.name,
    format: format.shape,
    example: format.examples[0],
    notes: std.stabilityNote,
  }));
});

/** Merge database rows with the built-in set, preferring stored rows by key. */
export function mergeStandards(rows: Record<string, unknown>[]): StandardEntry[] {
  const merged = new Map<string, StandardEntry>();
  for (const entry of BUILT_IN_STANDARDS) merged.set(entry.key, entry);
  for (const row of rows) {
    const key = String(row["key"] ?? "").trim();
    const title = String(row["title"] ?? "").trim();
    const body = String(row["body"] ?? "").trim();
    if (!key || !title || !body) continue;
    merged.set(key, {
      key,
      title,
      body,
      sort_order: Number(row["sort_order"] ?? merged.get(key)?.sort_order ?? 999) || 999,
    });
  }
  return [...merged.values()].sort(
    (a, b) => a.sort_order - b.sort_order || a.key.localeCompare(b.key),
  );
}
