// Admin-only vault encryption key journal + guided key change flow.
//
// Why this exists: the vault key lives in server configuration
// (VAULT_ENCRYPTION_KEY). If anything replaces that value — a hardening pass, a
// redeploy from a different env file, a secret regenerated by hand — the app
// silently starts sealing with the new key and every older entry fails to open
// with "not the key this entry was encrypted with".
//
// The journal records the *fingerprint* of the key the server is running with
// (never the key itself). Any time the fingerprint differs from the last one
// recorded, that is logged as `key_changed`, so a silent swap becomes visible
// evidence with a timestamp instead of a mystery.
import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { requireVaultAdmin } from "./vault-recovery.server";

export type VaultKeyEvent =
  | "observed"
  | "key_changed"
  | "change_acknowledged"
  | "change_started"
  | "change_completed";

export interface VaultKeyJournalEntry {
  id: string;
  fingerprint: string;
  keyShape: string;
  event: VaultKeyEvent;
  note: string | null;
  rowsTotal: number | null;
  rowsReadable: number | null;
  createdAt: string;
}

export interface VaultKeyHealth {
  configured: boolean;
  primaryFingerprint: string | null;
  primaryShape: string | null;
  oldFingerprint: string | null;
  oldKeyPresent: boolean;
  /** Readability of the actual stored rows with the keys currently loaded. */
  rowsTotal: number;
  rowsReadable: number;
  rowsUnreadable: number;
  /** Fingerprint of the last key the journal saw, if any. */
  lastJournalFingerprint: string | null;
  lastJournalAt: string | null;
  /** True when the running key differs from the last journalled key. */
  keyChangedSinceLastRecord: boolean;
  journal: VaultKeyJournalEntry[];
}

interface JournalRow {
  id: string;
  fingerprint: string;
  key_shape: string;
  event: VaultKeyEvent;
  note: string | null;
  rows_total: number | null;
  rows_readable: number | null;
  created_at: string;
}

function mapRow(r: JournalRow): VaultKeyJournalEntry {
  return {
    id: r.id,
    fingerprint: r.fingerprint,
    keyShape: r.key_shape,
    event: r.event,
    note: r.note,
    rowsTotal: r.rows_total,
    rowsReadable: r.rows_readable,
    createdAt: r.created_at,
  };
}

/** Count how many stored rows the currently loaded keys can actually open. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function measureReadability(supabase: any): Promise<{ total: number; readable: number }> {
  const { tryOpenIdentify } = await import("./vault-crypto.server");
  const { data, error } = await supabase
    .from("vault_secrets")
    .select("id, value_ciphertext, value_iv, value_tag");
  if (error) throw new Error(error.message);
  let readable = 0;
  for (const row of data ?? []) {
    const r = row as { value_ciphertext: string; value_iv: string; value_tag: string };
    try {
      const opened = await tryOpenIdentify({
        ciphertext: r.value_ciphertext,
        iv: r.value_iv,
        tag: r.value_tag,
      });
      if (opened) readable++;
    } catch {
      /* unreadable */
    }
  }
  return { total: data?.length ?? 0, readable };
}

/** Health + journal in one call. Also auto-appends a `key_changed` entry the
 *  first time a new fingerprint is seen, so the swap is dated permanently. */
export const getVaultKeyHealth = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }): Promise<VaultKeyHealth> => {
    await requireVaultAdmin(context.supabase, context.userId);

    const raw = process.env.VAULT_ENCRYPTION_KEY;
    const { data: journalRows, error: jErr } = await context.supabase
      .from("vault_key_journal")
      .select("id, fingerprint, key_shape, event, note, rows_total, rows_readable, created_at")
      .order("created_at", { ascending: false })
      .limit(50);
    if (jErr) throw new Error(jErr.message);
    const journal = ((journalRows ?? []) as JournalRow[]).map(mapRow);
    const lastKeyEntry = journal.find((e) => e.event !== "change_acknowledged") ?? null;

    if (!raw) {
      return {
        configured: false,
        primaryFingerprint: null,
        primaryShape: null,
        oldFingerprint: null,
        oldKeyPresent: Boolean(process.env.VAULT_ENCRYPTION_KEY_OLD),
        rowsTotal: 0,
        rowsReadable: 0,
        rowsUnreadable: 0,
        lastJournalFingerprint: lastKeyEntry?.fingerprint ?? null,
        lastJournalAt: lastKeyEntry?.createdAt ?? null,
        keyChangedSinceLastRecord: false,
        journal,
      };
    }

    const { getKeyFingerprints, describeKeyShape } = await import("./vault-crypto.server");
    const fp = await getKeyFingerprints();
    const shape = describeKeyShape(raw);
    const { total, readable } = await measureReadability(context.supabase);

    const changed = Boolean(lastKeyEntry && lastKeyEntry.fingerprint !== fp.primary);

    // Record the first sighting of this fingerprint so it is permanently dated.
    if (!lastKeyEntry || changed) {
      const { error: insErr } = await context.supabase.from("vault_key_journal").insert({
        fingerprint: fp.primary,
        key_shape: shape,
        event: changed ? "key_changed" : "observed",
        note: changed
          ? `Running key differs from the last recorded key (${lastKeyEntry?.fingerprint}). Detected automatically.`
          : "First recorded sighting of this key.",
        rows_total: total,
        rows_readable: readable,
        recorded_by: context.userId,
      });
      if (!insErr) {
        const fresh: VaultKeyJournalEntry = {
          id: "pending",
          fingerprint: fp.primary,
          keyShape: shape,
          event: changed ? "key_changed" : "observed",
          note: changed ? "Detected automatically." : "First recorded sighting of this key.",
          rowsTotal: total,
          rowsReadable: readable,
          createdAt: new Date().toISOString(),
        };
        journal.unshift(fresh);
      }
    }

    return {
      configured: true,
      primaryFingerprint: fp.primary,
      primaryShape: shape,
      oldFingerprint: fp.old,
      oldKeyPresent: fp.old !== null,
      rowsTotal: total,
      rowsReadable: readable,
      rowsUnreadable: total - readable,
      lastJournalFingerprint: lastKeyEntry?.fingerprint ?? null,
      lastJournalAt: lastKeyEntry?.createdAt ?? null,
      keyChangedSinceLastRecord: changed,
      journal,
    };
  });

/** Append an operator note to the journal: acknowledging a detected change,
 *  declaring a planned change, or closing one out. Never accepts key material. */
export const recordVaultKeyEvent = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: { event: VaultKeyEvent; note: string }) => {
    const allowed: VaultKeyEvent[] = [
      "change_acknowledged",
      "change_started",
      "change_completed",
    ];
    if (!allowed.includes(d.event)) throw new Error("Unsupported journal event");
    const note = String(d.note ?? "").trim();
    if (note.length < 3) throw new Error("Write a short note describing what happened.");
    if (/^[0-9a-fA-F]{64}$/.test(note)) {
      throw new Error("That looks like a key value. Notes must never contain key material.");
    }
    return { event: d.event, note: note.slice(0, 500) };
  })
  .handler(async ({ context, data }): Promise<{ ok: true }> => {
    await requireVaultAdmin(context.supabase, context.userId);
    const raw = process.env.VAULT_ENCRYPTION_KEY;
    let fingerprint = "unset";
    let shape = "not configured";
    if (raw) {
      const { getKeyFingerprints, describeKeyShape } = await import("./vault-crypto.server");
      fingerprint = (await getKeyFingerprints()).primary;
      shape = describeKeyShape(raw);
    }
    const { total, readable } = await measureReadability(context.supabase);
    const { error } = await context.supabase.from("vault_key_journal").insert({
      fingerprint,
      key_shape: shape,
      event: data.event,
      note: data.note,
      rows_total: total,
      rows_readable: readable,
      recorded_by: context.userId,
    });
    if (error) throw new Error(error.message);
    return { ok: true };
  });
