import {describe,expect,it} from "vitest";import {assertCredentialReference,evaluateAiProvider,toBackupSafeAiConfiguration,type AiProviderConfiguration} from "../src/lib/desktop/ai-provider";
const local:AiProviderConfiguration={id:"ollama",mode:"local",provider:"ollama",endpoint:"http://127.0.0.1:11434/v1",credentialReference:null,allowedModules:["procedures"],dataLeavesDevice:false,enabled:true};
describe("desktop AI provider boundary",()=>{it("allows a local provider without a secret",()=>expect(evaluateAiProvider(local,"procedures",true)).toEqual({ready:true}));
it("requires module authorization and AI entitlement independently",()=>{expect(evaluateAiProvider(local,"inventory",true)).toEqual({ready:false,reason:"module-not-authorized"});expect(evaluateAiProvider(local,"procedures",false)).toEqual({ready:false,reason:"entitlement-required"});});
it("requires remote transport and a vault credential reference",()=>{const remote={...local,mode:"byok" as const,provider:"openai-compatible" as const,endpoint:"http://provider.example/v1",dataLeavesDevice:true,credentialReference:null};expect(evaluateAiProvider(remote,"procedures",true)).toEqual({ready:false,reason:"credential-required"});const withKey={...remote,credentialReference:"secret-service://farmops/openai"};expect(evaluateAiProvider(withKey,"procedures",true)).toEqual({ready:false,reason:"insecure-remote-endpoint"});expect(()=>assertCredentialReference("plain-text-api-key")).toThrow(/credential vault/);expect(()=>assertCredentialReference(withKey.credentialReference)).not.toThrow();});
it("requires an explicit BYOK endpoint",()=>{const byokWithoutEndpoint={...local,mode:"byok" as const,provider:"openai-compatible" as const,endpoint:" ",credentialReference:"secret-service://farmops/openai",dataLeavesDevice:true};expect(evaluateAiProvider(byokWithoutEndpoint,"procedures",true)).toEqual({ready:false,reason:"endpoint-required"});});
it("rejects BYOK and FarmOps credentials outside the OS vault",()=>{const badByok={...local,mode:"byok" as const,provider:"openai-compatible" as const,endpoint:"https://api.example/v1",credentialReference:"plain-api-key",dataLeavesDevice:true};expect(evaluateAiProvider(badByok,"procedures",true)).toEqual({ready:false,reason:"credential-required"});const badFarmOps={...local,mode:"farmops" as const,provider:"farmops" as const,endpoint:"https://farmops.example/v1",credentialReference:"api-key",dataLeavesDevice:true};expect(evaluateAiProvider(badFarmOps,"procedures",true)).toEqual({ready:false,reason:"credential-required"});});
it("keeps local mode on loopback endpoints only",()=>{const nonLoopback={...local,endpoint:"https://remote.example/v1"};expect(evaluateAiProvider(nonLoopback,"procedures",true)).toEqual({ready:false,reason:"insecure-remote-endpoint"});});
it("strips credential references from backup configuration",()=>{const configured={...local,mode:"byok" as const,provider:"openai-compatible" as const,endpoint:"https://api.example/v1",dataLeavesDevice:true,credentialReference:"windows-credential-manager://farmops/openai"};const safe=toBackupSafeAiConfiguration(configured);expect(safe.credentialConfigured).toBe(true);expect(safe.credentialReference).toBeNull();expect(JSON.stringify(safe)).not.toContain("windows-credential-manager");});});
