import { app, BrowserWindow, dialog, ipcMain } from "electron";
import fs from "node:fs"; import path from "node:path"; import crypto from "node:crypto"; import {fileURLToPath} from "node:url"; import { openProfileDatabase, DESKTOP_SCHEMA_VERSION } from "./local-storage.mjs"; import { buildDesktopHealthHtml } from "./health-screen.mjs"; import {configureBackupFolder} from "./backup-folder-setup.mjs";

let profileDatabase;
if (!app.requestSingleInstanceLock()) app.quit();
function ensureIdentity(root){const file=path.join(root,"installation.json");fs.mkdirSync(root,{recursive:true});if(!fs.existsSync(file))fs.writeFileSync(file,JSON.stringify({installationId:crypto.randomUUID(),deviceId:crypto.randomUUID(),createdAt:new Date().toISOString()},null,2));}
function registerDesktopHandlers(userData){ipcMain.handle("farmops:select-backup-destination",async()=>{const selection=await dialog.showOpenDialog({title:"Select FarmOps backup destination",properties:["openDirectory","createDirectory"]});if(selection.canceled||selection.filePaths.length!==1)return {configured:false,canceled:true};try{return configureBackupFolder({userDataRoot:userData,directory:selection.filePaths[0]});}catch(error){return {configured:false,canceled:false,error:error instanceof Error?error.message:"Backup destination failed"};}});}
function createWindow(){const userData=app.getPath("userData");ensureIdentity(userData);registerDesktopHandlers(userData);const profileType=process.env.FARMOPS_PROFILE??"demo";const opened=openProfileDatabase(userData,profileType);profileDatabase=opened.db;const window=new BrowserWindow({width:1440,height:900,webPreferences:{contextIsolation:true,sandbox:true,nodeIntegration:false,preload:path.join(path.dirname(fileURLToPath(import.meta.url)),"preload.mjs")}});const url=process.env.FARMOPS_DESKTOP_URL;if(url)window.loadURL(url);else window.loadURL("data:text/html;charset=utf-8,"+encodeURIComponent(buildDesktopHealthHtml({profileType,schemaVersion:DESKTOP_SCHEMA_VERSION,databasePath:opened.profile.database,appVersion:app.getVersion()})));}
app.whenReady().then(createWindow);app.on("before-quit",()=>{profileDatabase?.close();profileDatabase=undefined;});app.on("window-all-closed",()=>{if(process.platform!=="darwin")app.quit();});
