#!/usr/bin/env bash
# Configure the self-hosted backend so its database, pooler, and API gateway
# remain reachable only through the shared Docker network. Caddy is the only
# service that should publish ports 80/443 on the host.

set -euo pipefail

SUPABASE_DIR="/home/rpremo/supabase-project"
APPLY=1

while [ $# -gt 0 ]; do
  case "$1" in
    --supabase-dir) shift; SUPABASE_DIR="${1:-}" ;;
    --supabase-dir=*) SUPABASE_DIR="${1#*=}" ;;
    --no-apply) APPLY=0 ;;
    -h|--help) sed -n '2,18p' "$0"; exit 0 ;;
    *) echo "Unknown flag: $1" >&2; exit 2 ;;
  esac
  shift || true
done

STACK_DIR="$SUPABASE_DIR/docker"
[ -f "$STACK_DIR/docker-compose.yml" ] || STACK_DIR="$SUPABASE_DIR"
COMPOSE_FILE_PATH="$STACK_DIR/docker-compose.yml"
ENV_FILE="$STACK_DIR/.env"
OVERRIDE_NAME="docker-compose.hardening.yml"
OVERRIDE_PATH="$STACK_DIR/$OVERRIDE_NAME"

if [ ! -f "$COMPOSE_FILE_PATH" ]; then
  echo "FAIL: backend docker-compose.yml not found under $SUPABASE_DIR" >&2
  exit 1
fi
if [ ! -f "$ENV_FILE" ]; then
  echo "FAIL: backend .env not found at $ENV_FILE" >&2
  exit 1
fi

DOCKER=(docker)
if ! docker info >/dev/null 2>&1; then
  if command -v sudo >/dev/null 2>&1 && sudo -n docker info >/dev/null 2>&1; then
    DOCKER=(sudo -n docker)
  else
    echo "FAIL: cannot reach the Docker daemon" >&2
    exit 1
  fi
fi

# Read the base file directly so an old COMPOSE_FILE assignment cannot hide it.
mapfile -t SERVICES < <("${DOCKER[@]}" compose -f "$COMPOSE_FILE_PATH" --env-file "$ENV_FILE" config --services)
has_service() { printf '%s\n' "${SERVICES[@]}" | grep -qxF "$1"; }

GATEWAY=""
if has_service api-gw; then
  GATEWAY="api-gw"
elif has_service kong; then
  GATEWAY="kong"
fi

if [ -z "$GATEWAY" ]; then
  echo "FAIL: backend compose file defines neither 'api-gw' nor 'kong'" >&2
  exit 1
fi

TMP_OVERRIDE="$(mktemp)"
{
  echo "# Generated by FarmOps. Keeps backend data-plane ports off the host."
  echo "services:"
  printf '  %s:\n    ports: !override []\n' "$GATEWAY"
  if has_service supavisor; then
    printf '  supavisor:\n    ports: !override []\n'
  fi
  # Some older self-hosted bundles publish PostgreSQL directly.
  if has_service db; then
    printf '  db:\n    ports: !override []\n'
  fi
} > "$TMP_OVERRIDE"
mv "$TMP_OVERRIDE" "$OVERRIDE_PATH"

# Persist the compose layering without disturbing any other backend settings.
CURRENT="$(sed -n 's/^[[:space:]]*COMPOSE_FILE=//p' "$ENV_FILE" | tail -n1)"
if [ -z "$CURRENT" ]; then
  NEXT="docker-compose.yml:$OVERRIDE_NAME"
elif printf '%s' "$CURRENT" | tr ':' '\n' | grep -qxF "$OVERRIDE_NAME"; then
  NEXT="$CURRENT"
else
  NEXT="$CURRENT:$OVERRIDE_NAME"
fi

TMP_ENV="$(mktemp)"
awk -v next="$NEXT" '
  BEGIN { replaced = 0 }
  /^[[:space:]]*COMPOSE_FILE=/ {
    if (!replaced) print "COMPOSE_FILE=" next
    replaced = 1
    next
  }
  { print }
  END { if (!replaced) print "COMPOSE_FILE=" next }
' "$ENV_FILE" > "$TMP_ENV"
cat "$TMP_ENV" > "$ENV_FILE"
rm -f "$TMP_ENV"
chmod 600 "$ENV_FILE" "$OVERRIDE_PATH"

echo "PASS: backend hardening configured at $OVERRIDE_PATH"

if [ "$APPLY" -eq 1 ]; then
  echo "Applying backend network hardening…"
  TARGETS=("$GATEWAY")
  has_service supavisor && TARGETS+=(supavisor)
  has_service db && TARGETS+=(db)
  (
    cd "$STACK_DIR"
    COMPOSE_FILE="$NEXT" "${DOCKER[@]}" compose --env-file .env up -d "${TARGETS[@]}"
  )
fi