import {FARMOPS_MODULE_IDS,type FarmOpsModuleId} from "./entitlements";
export interface LicenseGrant {moduleId:FarmOpsModuleId;status:"active"|"inactive";plan:"subscription"|"trial_extension"|"manual";expiresAt:string|null;}
export interface LicensePayload {licenseVersion:1;customerId:string;installationId:string;issuedAt:string;offlineValidUntil:string;grants:readonly LicenseGrant[];}
export interface SignedLicenseDocument {payload:LicensePayload;signature:string;}
export type SignatureVerifier=(canonicalPayload:string,signature:string)=>boolean;
export type LicenseValidation={valid:true;payload:LicensePayload}|{valid:false;reason:"malformed"|"installation-mismatch"|"signature-invalid"|"not-yet-valid"|"offline-validation-expired"};
function canonical(value:unknown):string {if(Array.isArray(value))return `[${value.map(canonical).join(",")}]`;if(value&&typeof value==="object")return `{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${canonical(item)}`).join(",")}}`;return JSON.stringify(value);}
function instant(value:string):number {const result=Date.parse(value);if(!Number.isFinite(result))throw new Error("invalid timestamp");return result;}
export function validateSignedLicense(document:SignedLicenseDocument,expectedInstallationId:string,now:Date,verify:SignatureVerifier):LicenseValidation {const p=document?.payload;try{if(!p||p.licenseVersion!==1||!p.customerId||!p.installationId||!document.signature||instant(p.offlineValidUntil)<instant(p.issuedAt))return {valid:false,reason:"malformed"};}catch{return {valid:false,reason:"malformed"};}if(!p.grants.every(grant=>FARMOPS_MODULE_IDS.includes(grant.moduleId)&&(["active","inactive"] as const).includes(grant.status)&&grant.expiresAt!==undefined&&(grant.expiresAt===null||Number.isFinite(Date.parse(grant.expiresAt)))))return {valid:false,reason:"malformed"};if(p.installationId!==expectedInstallationId)return {valid:false,reason:"installation-mismatch"};if(!verify(canonical(p),document.signature))return {valid:false,reason:"signature-invalid"};if(now.getTime()<instant(p.issuedAt))return {valid:false,reason:"not-yet-valid"};if(now.getTime()>=instant(p.offlineValidUntil))return {valid:false,reason:"offline-validation-expired"};return {valid:true,payload:p};}
export function licensedModuleAccess(moduleId:FarmOpsModuleId,validation:LicenseValidation,now:Date):{access:"full"|"locked";source:"free_for_life"|"license";dataDisposition:"accessible"|"retained_locked"} {if(moduleId==="procedures")return {access:"full",source:"free_for_life",dataDisposition:"accessible"};if(!validation.valid)return {access:"locked",source:"license",dataDisposition:"retained_locked"};const grant=validation.payload.grants.find(item=>item.moduleId===moduleId&&item.status==="active"&&(item.expiresAt===null||now.getTime()<instant(item.expiresAt)));return grant?{access:"full",source:"license",dataDisposition:"accessible"}:{access:"locked",source:"license",dataDisposition:"retained_locked"};}
export const canonicalizeLicensePayload=canonical;
