/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as ServiceSchedulingRouteImport } from './routes/service-scheduling'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProceduresRouteImport } from './routes/procedures'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as FoodRouteImport } from './routes/food'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as FoodIndexRouteImport } from './routes/food.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TasksScheduledRouteImport } from './routes/tasks.scheduled'
import { Route as TasksBacklogRouteImport } from './routes/tasks.backlog'
import { Route as TasksSlugRouteImport } from './routes/tasks.$slug'
import { Route as SettingsSelfHostRouteImport } from './routes/settings.self-host'
import { Route as NotesDateRouteImport } from './routes/notes.$date'
import { Route as MaintenanceGenerateScheduleRouteImport } from './routes/maintenance.generate-schedule'
import { Route as MaintenanceForecastRouteImport } from './routes/maintenance.forecast'
import { Route as MaintenanceDiagnoseRouteImport } from './routes/maintenance.diagnose'
import { Route as FoodStorageRouteImport } from './routes/food.storage'
import { Route as FoodSeasonsRouteImport } from './routes/food.seasons'
import { Route as FoodReportsRouteImport } from './routes/food.reports'
import { Route as FoodProcessingRouteImport } from './routes/food.processing'
import { Route as FoodPricesRouteImport } from './routes/food.prices'
import { Route as FoodPreserveRouteImport } from './routes/food.preserve'
import { Route as FoodPlanRouteImport } from './routes/food.plan'
import { Route as FoodOrchardRouteImport } from './routes/food.orchard'
import { Route as FoodLivestockRouteImport } from './routes/food.livestock'
import { Route as FoodIrrigationRouteImport } from './routes/food.irrigation'
import { Route as FoodGardenRouteImport } from './routes/food.garden'
import { Route as FoodCropsRouteImport } from './routes/food.crops'
import { Route as AdminVaultRotationRouteImport } from './routes/admin.vault-rotation'
import { Route as AdminVaultBackupRouteImport } from './routes/admin.vault-backup'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSchemaRouteImport } from './routes/admin.schema'
import { Route as AdminRestoreRouteImport } from './routes/admin.restore'
import { Route as AdminResetRouteImport } from './routes/admin.reset'
import { Route as AdminExportKeyRouteImport } from './routes/admin.export-key'
import { Route as AdminExportRouteImport } from './routes/admin.export'
import { Route as ApiPublicWebhooksRachioRouteImport } from './routes/api/public/webhooks/rachio'
import { Route as ApiPublicHooksRachioSyncRouteImport } from './routes/api/public/hooks/rachio-sync'
import { Route as ApiPublicHealthProceduresRouteImport } from './routes/api/public/health.procedures'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSchedulingRoute = ServiceSchedulingRouteImport.update({
  id: '/service-scheduling',
  path: '/service-scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProceduresRoute = ProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodIndexRoute = FoodIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FoodRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksScheduledRoute = TasksScheduledRouteImport.update({
  id: '/tasks/scheduled',
  path: '/tasks/scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksBacklogRoute = TasksBacklogRouteImport.update({
  id: '/tasks/backlog',
  path: '/tasks/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksSlugRoute = TasksSlugRouteImport.update({
  id: '/tasks/$slug',
  path: '/tasks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSelfHostRoute = SettingsSelfHostRouteImport.update({
  id: '/settings/self-host',
  path: '/settings/self-host',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesDateRoute = NotesDateRouteImport.update({
  id: '/notes/$date',
  path: '/notes/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceGenerateScheduleRoute =
  MaintenanceGenerateScheduleRouteImport.update({
    id: '/generate-schedule',
    path: '/generate-schedule',
    getParentRoute: () => MaintenanceRoute,
  } as any)
const MaintenanceForecastRoute = MaintenanceForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => MaintenanceRoute,
} as any)
const MaintenanceDiagnoseRoute = MaintenanceDiagnoseRouteImport.update({
  id: '/diagnose',
  path: '/diagnose',
  getParentRoute: () => MaintenanceRoute,
} as any)
const FoodStorageRoute = FoodStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => FoodRoute,
} as any)
const FoodSeasonsRoute = FoodSeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => FoodRoute,
} as any)
const FoodReportsRoute = FoodReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => FoodRoute,
} as any)
const FoodProcessingRoute = FoodProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => FoodRoute,
} as any)
const FoodPricesRoute = FoodPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => FoodRoute,
} as any)
const FoodPreserveRoute = FoodPreserveRouteImport.update({
  id: '/preserve',
  path: '/preserve',
  getParentRoute: () => FoodRoute,
} as any)
const FoodPlanRoute = FoodPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => FoodRoute,
} as any)
const FoodOrchardRoute = FoodOrchardRouteImport.update({
  id: '/orchard',
  path: '/orchard',
  getParentRoute: () => FoodRoute,
} as any)
const FoodLivestockRoute = FoodLivestockRouteImport.update({
  id: '/livestock',
  path: '/livestock',
  getParentRoute: () => FoodRoute,
} as any)
const FoodIrrigationRoute = FoodIrrigationRouteImport.update({
  id: '/irrigation',
  path: '/irrigation',
  getParentRoute: () => FoodRoute,
} as any)
const FoodGardenRoute = FoodGardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => FoodRoute,
} as any)
const FoodCropsRoute = FoodCropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => FoodRoute,
} as any)
const AdminVaultRotationRoute = AdminVaultRotationRouteImport.update({
  id: '/admin/vault-rotation',
  path: '/admin/vault-rotation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVaultBackupRoute = AdminVaultBackupRouteImport.update({
  id: '/admin/vault-backup',
  path: '/admin/vault-backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSchemaRoute = AdminSchemaRouteImport.update({
  id: '/admin/schema',
  path: '/admin/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRestoreRoute = AdminRestoreRouteImport.update({
  id: '/admin/restore',
  path: '/admin/restore',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetRoute = AdminResetRouteImport.update({
  id: '/admin/reset',
  path: '/admin/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExportKeyRoute = AdminExportKeyRouteImport.update({
  id: '/admin/export-key',
  path: '/admin/export-key',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/admin/export',
  path: '/admin/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksRachioRoute = ApiPublicWebhooksRachioRouteImport.update({
  id: '/api/public/webhooks/rachio',
  path: '/api/public/webhooks/rachio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRachioSyncRoute =
  ApiPublicHooksRachioSyncRouteImport.update({
    id: '/api/public/hooks/rachio-sync',
    path: '/api/public/hooks/rachio-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHealthProceduresRoute =
  ApiPublicHealthProceduresRouteImport.update({
    id: '/api/public/health/procedures',
    path: '/api/public/health/procedures',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/food': typeof FoodRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/maintenance': typeof MaintenanceRouteWithChildren
  '/procedures': typeof ProceduresRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-scheduling': typeof ServiceSchedulingRoute
  '/sync': typeof SyncRoute
  '/vault': typeof VaultRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/export-key': typeof AdminExportKeyRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin/restore': typeof AdminRestoreRoute
  '/admin/schema': typeof AdminSchemaRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vault-backup': typeof AdminVaultBackupRoute
  '/admin/vault-rotation': typeof AdminVaultRotationRoute
  '/food/crops': typeof FoodCropsRoute
  '/food/garden': typeof FoodGardenRoute
  '/food/irrigation': typeof FoodIrrigationRoute
  '/food/livestock': typeof FoodLivestockRoute
  '/food/orchard': typeof FoodOrchardRoute
  '/food/plan': typeof FoodPlanRoute
  '/food/preserve': typeof FoodPreserveRoute
  '/food/prices': typeof FoodPricesRoute
  '/food/processing': typeof FoodProcessingRoute
  '/food/reports': typeof FoodReportsRoute
  '/food/seasons': typeof FoodSeasonsRoute
  '/food/storage': typeof FoodStorageRoute
  '/maintenance/diagnose': typeof MaintenanceDiagnoseRoute
  '/maintenance/forecast': typeof MaintenanceForecastRoute
  '/maintenance/generate-schedule': typeof MaintenanceGenerateScheduleRoute
  '/notes/$date': typeof NotesDateRoute
  '/settings/self-host': typeof SettingsSelfHostRoute
  '/tasks/$slug': typeof TasksSlugRoute
  '/tasks/backlog': typeof TasksBacklogRoute
  '/tasks/scheduled': typeof TasksScheduledRoute
  '/admin/': typeof AdminIndexRoute
  '/food/': typeof FoodIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/public/health/procedures': typeof ApiPublicHealthProceduresRoute
  '/api/public/hooks/rachio-sync': typeof ApiPublicHooksRachioSyncRoute
  '/api/public/webhooks/rachio': typeof ApiPublicWebhooksRachioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/maintenance': typeof MaintenanceRouteWithChildren
  '/procedures': typeof ProceduresRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-scheduling': typeof ServiceSchedulingRoute
  '/sync': typeof SyncRoute
  '/vault': typeof VaultRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/export-key': typeof AdminExportKeyRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin/restore': typeof AdminRestoreRoute
  '/admin/schema': typeof AdminSchemaRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vault-backup': typeof AdminVaultBackupRoute
  '/admin/vault-rotation': typeof AdminVaultRotationRoute
  '/food/crops': typeof FoodCropsRoute
  '/food/garden': typeof FoodGardenRoute
  '/food/irrigation': typeof FoodIrrigationRoute
  '/food/livestock': typeof FoodLivestockRoute
  '/food/orchard': typeof FoodOrchardRoute
  '/food/plan': typeof FoodPlanRoute
  '/food/preserve': typeof FoodPreserveRoute
  '/food/prices': typeof FoodPricesRoute
  '/food/processing': typeof FoodProcessingRoute
  '/food/reports': typeof FoodReportsRoute
  '/food/seasons': typeof FoodSeasonsRoute
  '/food/storage': typeof FoodStorageRoute
  '/maintenance/diagnose': typeof MaintenanceDiagnoseRoute
  '/maintenance/forecast': typeof MaintenanceForecastRoute
  '/maintenance/generate-schedule': typeof MaintenanceGenerateScheduleRoute
  '/notes/$date': typeof NotesDateRoute
  '/settings/self-host': typeof SettingsSelfHostRoute
  '/tasks/$slug': typeof TasksSlugRoute
  '/tasks/backlog': typeof TasksBacklogRoute
  '/tasks/scheduled': typeof TasksScheduledRoute
  '/admin': typeof AdminIndexRoute
  '/food': typeof FoodIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/api/public/health/procedures': typeof ApiPublicHealthProceduresRoute
  '/api/public/hooks/rachio-sync': typeof ApiPublicHooksRachioSyncRoute
  '/api/public/webhooks/rachio': typeof ApiPublicWebhooksRachioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/food': typeof FoodRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/maintenance': typeof MaintenanceRouteWithChildren
  '/procedures': typeof ProceduresRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-scheduling': typeof ServiceSchedulingRoute
  '/sync': typeof SyncRoute
  '/vault': typeof VaultRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/export-key': typeof AdminExportKeyRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin/restore': typeof AdminRestoreRoute
  '/admin/schema': typeof AdminSchemaRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vault-backup': typeof AdminVaultBackupRoute
  '/admin/vault-rotation': typeof AdminVaultRotationRoute
  '/food/crops': typeof FoodCropsRoute
  '/food/garden': typeof FoodGardenRoute
  '/food/irrigation': typeof FoodIrrigationRoute
  '/food/livestock': typeof FoodLivestockRoute
  '/food/orchard': typeof FoodOrchardRoute
  '/food/plan': typeof FoodPlanRoute
  '/food/preserve': typeof FoodPreserveRoute
  '/food/prices': typeof FoodPricesRoute
  '/food/processing': typeof FoodProcessingRoute
  '/food/reports': typeof FoodReportsRoute
  '/food/seasons': typeof FoodSeasonsRoute
  '/food/storage': typeof FoodStorageRoute
  '/maintenance/diagnose': typeof MaintenanceDiagnoseRoute
  '/maintenance/forecast': typeof MaintenanceForecastRoute
  '/maintenance/generate-schedule': typeof MaintenanceGenerateScheduleRoute
  '/notes/$date': typeof NotesDateRoute
  '/settings/self-host': typeof SettingsSelfHostRoute
  '/tasks/$slug': typeof TasksSlugRoute
  '/tasks/backlog': typeof TasksBacklogRoute
  '/tasks/scheduled': typeof TasksScheduledRoute
  '/admin/': typeof AdminIndexRoute
  '/food/': typeof FoodIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/public/health/procedures': typeof ApiPublicHealthProceduresRoute
  '/api/public/hooks/rachio-sync': typeof ApiPublicHooksRachioSyncRoute
  '/api/public/webhooks/rachio': typeof ApiPublicWebhooksRachioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/food'
    | '/inventory'
    | '/maintenance'
    | '/procedures'
    | '/projects'
    | '/reports'
    | '/reset-password'
    | '/service-scheduling'
    | '/sync'
    | '/vault'
    | '/admin/export'
    | '/admin/export-key'
    | '/admin/reset'
    | '/admin/restore'
    | '/admin/schema'
    | '/admin/users'
    | '/admin/vault-backup'
    | '/admin/vault-rotation'
    | '/food/crops'
    | '/food/garden'
    | '/food/irrigation'
    | '/food/livestock'
    | '/food/orchard'
    | '/food/plan'
    | '/food/preserve'
    | '/food/prices'
    | '/food/processing'
    | '/food/reports'
    | '/food/seasons'
    | '/food/storage'
    | '/maintenance/diagnose'
    | '/maintenance/forecast'
    | '/maintenance/generate-schedule'
    | '/notes/$date'
    | '/settings/self-host'
    | '/tasks/$slug'
    | '/tasks/backlog'
    | '/tasks/scheduled'
    | '/admin/'
    | '/food/'
    | '/tasks/'
    | '/api/public/health/procedures'
    | '/api/public/hooks/rachio-sync'
    | '/api/public/webhooks/rachio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/inventory'
    | '/maintenance'
    | '/procedures'
    | '/projects'
    | '/reports'
    | '/reset-password'
    | '/service-scheduling'
    | '/sync'
    | '/vault'
    | '/admin/export'
    | '/admin/export-key'
    | '/admin/reset'
    | '/admin/restore'
    | '/admin/schema'
    | '/admin/users'
    | '/admin/vault-backup'
    | '/admin/vault-rotation'
    | '/food/crops'
    | '/food/garden'
    | '/food/irrigation'
    | '/food/livestock'
    | '/food/orchard'
    | '/food/plan'
    | '/food/preserve'
    | '/food/prices'
    | '/food/processing'
    | '/food/reports'
    | '/food/seasons'
    | '/food/storage'
    | '/maintenance/diagnose'
    | '/maintenance/forecast'
    | '/maintenance/generate-schedule'
    | '/notes/$date'
    | '/settings/self-host'
    | '/tasks/$slug'
    | '/tasks/backlog'
    | '/tasks/scheduled'
    | '/admin'
    | '/food'
    | '/tasks'
    | '/api/public/health/procedures'
    | '/api/public/hooks/rachio-sync'
    | '/api/public/webhooks/rachio'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/food'
    | '/inventory'
    | '/maintenance'
    | '/procedures'
    | '/projects'
    | '/reports'
    | '/reset-password'
    | '/service-scheduling'
    | '/sync'
    | '/vault'
    | '/admin/export'
    | '/admin/export-key'
    | '/admin/reset'
    | '/admin/restore'
    | '/admin/schema'
    | '/admin/users'
    | '/admin/vault-backup'
    | '/admin/vault-rotation'
    | '/food/crops'
    | '/food/garden'
    | '/food/irrigation'
    | '/food/livestock'
    | '/food/orchard'
    | '/food/plan'
    | '/food/preserve'
    | '/food/prices'
    | '/food/processing'
    | '/food/reports'
    | '/food/seasons'
    | '/food/storage'
    | '/maintenance/diagnose'
    | '/maintenance/forecast'
    | '/maintenance/generate-schedule'
    | '/notes/$date'
    | '/settings/self-host'
    | '/tasks/$slug'
    | '/tasks/backlog'
    | '/tasks/scheduled'
    | '/admin/'
    | '/food/'
    | '/tasks/'
    | '/api/public/health/procedures'
    | '/api/public/hooks/rachio-sync'
    | '/api/public/webhooks/rachio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  FoodRoute: typeof FoodRouteWithChildren
  InventoryRoute: typeof InventoryRoute
  MaintenanceRoute: typeof MaintenanceRouteWithChildren
  ProceduresRoute: typeof ProceduresRoute
  ProjectsRoute: typeof ProjectsRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServiceSchedulingRoute: typeof ServiceSchedulingRoute
  SyncRoute: typeof SyncRoute
  VaultRoute: typeof VaultRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminExportKeyRoute: typeof AdminExportKeyRoute
  AdminResetRoute: typeof AdminResetRoute
  AdminRestoreRoute: typeof AdminRestoreRoute
  AdminSchemaRoute: typeof AdminSchemaRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVaultBackupRoute: typeof AdminVaultBackupRoute
  AdminVaultRotationRoute: typeof AdminVaultRotationRoute
  NotesDateRoute: typeof NotesDateRoute
  SettingsSelfHostRoute: typeof SettingsSelfHostRoute
  TasksSlugRoute: typeof TasksSlugRoute
  TasksBacklogRoute: typeof TasksBacklogRoute
  TasksScheduledRoute: typeof TasksScheduledRoute
  AdminIndexRoute: typeof AdminIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  ApiPublicHealthProceduresRoute: typeof ApiPublicHealthProceduresRoute
  ApiPublicHooksRachioSyncRoute: typeof ApiPublicHooksRachioSyncRoute
  ApiPublicWebhooksRachioRoute: typeof ApiPublicWebhooksRachioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-scheduling': {
      id: '/service-scheduling'
      path: '/service-scheduling'
      fullPath: '/service-scheduling'
      preLoaderRoute: typeof ServiceSchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedures': {
      id: '/procedures'
      path: '/procedures'
      fullPath: '/procedures'
      preLoaderRoute: typeof ProceduresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/': {
      id: '/food/'
      path: '/'
      fullPath: '/food/'
      preLoaderRoute: typeof FoodIndexRouteImport
      parentRoute: typeof FoodRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/scheduled': {
      id: '/tasks/scheduled'
      path: '/tasks/scheduled'
      fullPath: '/tasks/scheduled'
      preLoaderRoute: typeof TasksScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/backlog': {
      id: '/tasks/backlog'
      path: '/tasks/backlog'
      fullPath: '/tasks/backlog'
      preLoaderRoute: typeof TasksBacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$slug': {
      id: '/tasks/$slug'
      path: '/tasks/$slug'
      fullPath: '/tasks/$slug'
      preLoaderRoute: typeof TasksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/self-host': {
      id: '/settings/self-host'
      path: '/settings/self-host'
      fullPath: '/settings/self-host'
      preLoaderRoute: typeof SettingsSelfHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$date': {
      id: '/notes/$date'
      path: '/notes/$date'
      fullPath: '/notes/$date'
      preLoaderRoute: typeof NotesDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/generate-schedule': {
      id: '/maintenance/generate-schedule'
      path: '/generate-schedule'
      fullPath: '/maintenance/generate-schedule'
      preLoaderRoute: typeof MaintenanceGenerateScheduleRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/maintenance/forecast': {
      id: '/maintenance/forecast'
      path: '/forecast'
      fullPath: '/maintenance/forecast'
      preLoaderRoute: typeof MaintenanceForecastRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/maintenance/diagnose': {
      id: '/maintenance/diagnose'
      path: '/diagnose'
      fullPath: '/maintenance/diagnose'
      preLoaderRoute: typeof MaintenanceDiagnoseRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/food/storage': {
      id: '/food/storage'
      path: '/storage'
      fullPath: '/food/storage'
      preLoaderRoute: typeof FoodStorageRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/seasons': {
      id: '/food/seasons'
      path: '/seasons'
      fullPath: '/food/seasons'
      preLoaderRoute: typeof FoodSeasonsRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/reports': {
      id: '/food/reports'
      path: '/reports'
      fullPath: '/food/reports'
      preLoaderRoute: typeof FoodReportsRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/processing': {
      id: '/food/processing'
      path: '/processing'
      fullPath: '/food/processing'
      preLoaderRoute: typeof FoodProcessingRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/prices': {
      id: '/food/prices'
      path: '/prices'
      fullPath: '/food/prices'
      preLoaderRoute: typeof FoodPricesRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/preserve': {
      id: '/food/preserve'
      path: '/preserve'
      fullPath: '/food/preserve'
      preLoaderRoute: typeof FoodPreserveRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/plan': {
      id: '/food/plan'
      path: '/plan'
      fullPath: '/food/plan'
      preLoaderRoute: typeof FoodPlanRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/orchard': {
      id: '/food/orchard'
      path: '/orchard'
      fullPath: '/food/orchard'
      preLoaderRoute: typeof FoodOrchardRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/livestock': {
      id: '/food/livestock'
      path: '/livestock'
      fullPath: '/food/livestock'
      preLoaderRoute: typeof FoodLivestockRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/irrigation': {
      id: '/food/irrigation'
      path: '/irrigation'
      fullPath: '/food/irrigation'
      preLoaderRoute: typeof FoodIrrigationRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/garden': {
      id: '/food/garden'
      path: '/garden'
      fullPath: '/food/garden'
      preLoaderRoute: typeof FoodGardenRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/crops': {
      id: '/food/crops'
      path: '/crops'
      fullPath: '/food/crops'
      preLoaderRoute: typeof FoodCropsRouteImport
      parentRoute: typeof FoodRoute
    }
    '/admin/vault-rotation': {
      id: '/admin/vault-rotation'
      path: '/admin/vault-rotation'
      fullPath: '/admin/vault-rotation'
      preLoaderRoute: typeof AdminVaultRotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vault-backup': {
      id: '/admin/vault-backup'
      path: '/admin/vault-backup'
      fullPath: '/admin/vault-backup'
      preLoaderRoute: typeof AdminVaultBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schema': {
      id: '/admin/schema'
      path: '/admin/schema'
      fullPath: '/admin/schema'
      preLoaderRoute: typeof AdminSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/restore': {
      id: '/admin/restore'
      path: '/admin/restore'
      fullPath: '/admin/restore'
      preLoaderRoute: typeof AdminRestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset': {
      id: '/admin/reset'
      path: '/admin/reset'
      fullPath: '/admin/reset'
      preLoaderRoute: typeof AdminResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/export-key': {
      id: '/admin/export-key'
      path: '/admin/export-key'
      fullPath: '/admin/export-key'
      preLoaderRoute: typeof AdminExportKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/admin/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/rachio': {
      id: '/api/public/webhooks/rachio'
      path: '/api/public/webhooks/rachio'
      fullPath: '/api/public/webhooks/rachio'
      preLoaderRoute: typeof ApiPublicWebhooksRachioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/rachio-sync': {
      id: '/api/public/hooks/rachio-sync'
      path: '/api/public/hooks/rachio-sync'
      fullPath: '/api/public/hooks/rachio-sync'
      preLoaderRoute: typeof ApiPublicHooksRachioSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/procedures': {
      id: '/api/public/health/procedures'
      path: '/api/public/health/procedures'
      fullPath: '/api/public/health/procedures'
      preLoaderRoute: typeof ApiPublicHealthProceduresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FoodRouteChildren {
  FoodCropsRoute: typeof FoodCropsRoute
  FoodGardenRoute: typeof FoodGardenRoute
  FoodIrrigationRoute: typeof FoodIrrigationRoute
  FoodLivestockRoute: typeof FoodLivestockRoute
  FoodOrchardRoute: typeof FoodOrchardRoute
  FoodPlanRoute: typeof FoodPlanRoute
  FoodPreserveRoute: typeof FoodPreserveRoute
  FoodPricesRoute: typeof FoodPricesRoute
  FoodProcessingRoute: typeof FoodProcessingRoute
  FoodReportsRoute: typeof FoodReportsRoute
  FoodSeasonsRoute: typeof FoodSeasonsRoute
  FoodStorageRoute: typeof FoodStorageRoute
  FoodIndexRoute: typeof FoodIndexRoute
}

const FoodRouteChildren: FoodRouteChildren = {
  FoodCropsRoute: FoodCropsRoute,
  FoodGardenRoute: FoodGardenRoute,
  FoodIrrigationRoute: FoodIrrigationRoute,
  FoodLivestockRoute: FoodLivestockRoute,
  FoodOrchardRoute: FoodOrchardRoute,
  FoodPlanRoute: FoodPlanRoute,
  FoodPreserveRoute: FoodPreserveRoute,
  FoodPricesRoute: FoodPricesRoute,
  FoodProcessingRoute: FoodProcessingRoute,
  FoodReportsRoute: FoodReportsRoute,
  FoodSeasonsRoute: FoodSeasonsRoute,
  FoodStorageRoute: FoodStorageRoute,
  FoodIndexRoute: FoodIndexRoute,
}

const FoodRouteWithChildren = FoodRoute._addFileChildren(FoodRouteChildren)

interface MaintenanceRouteChildren {
  MaintenanceDiagnoseRoute: typeof MaintenanceDiagnoseRoute
  MaintenanceForecastRoute: typeof MaintenanceForecastRoute
  MaintenanceGenerateScheduleRoute: typeof MaintenanceGenerateScheduleRoute
}

const MaintenanceRouteChildren: MaintenanceRouteChildren = {
  MaintenanceDiagnoseRoute: MaintenanceDiagnoseRoute,
  MaintenanceForecastRoute: MaintenanceForecastRoute,
  MaintenanceGenerateScheduleRoute: MaintenanceGenerateScheduleRoute,
}

const MaintenanceRouteWithChildren = MaintenanceRoute._addFileChildren(
  MaintenanceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  FoodRoute: FoodRouteWithChildren,
  InventoryRoute: InventoryRoute,
  MaintenanceRoute: MaintenanceRouteWithChildren,
  ProceduresRoute: ProceduresRoute,
  ProjectsRoute: ProjectsRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServiceSchedulingRoute: ServiceSchedulingRoute,
  SyncRoute: SyncRoute,
  VaultRoute: VaultRoute,
  AdminExportRoute: AdminExportRoute,
  AdminExportKeyRoute: AdminExportKeyRoute,
  AdminResetRoute: AdminResetRoute,
  AdminRestoreRoute: AdminRestoreRoute,
  AdminSchemaRoute: AdminSchemaRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVaultBackupRoute: AdminVaultBackupRoute,
  AdminVaultRotationRoute: AdminVaultRotationRoute,
  NotesDateRoute: NotesDateRoute,
  SettingsSelfHostRoute: SettingsSelfHostRoute,
  TasksSlugRoute: TasksSlugRoute,
  TasksBacklogRoute: TasksBacklogRoute,
  TasksScheduledRoute: TasksScheduledRoute,
  AdminIndexRoute: AdminIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  ApiPublicHealthProceduresRoute: ApiPublicHealthProceduresRoute,
  ApiPublicHooksRachioSyncRoute: ApiPublicHooksRachioSyncRoute,
  ApiPublicWebhooksRachioRoute: ApiPublicWebhooksRachioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
