/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as ServiceSchedulingRouteImport } from './routes/service-scheduling'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as FoodRouteImport } from './routes/food'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as FoodIndexRouteImport } from './routes/food.index'
import { Route as TasksScheduledRouteImport } from './routes/tasks.scheduled'
import { Route as TasksBacklogRouteImport } from './routes/tasks.backlog'
import { Route as TasksSlugRouteImport } from './routes/tasks.$slug'
import { Route as NotesDateRouteImport } from './routes/notes.$date'
import { Route as FoodStorageRouteImport } from './routes/food.storage'
import { Route as FoodSeasonsRouteImport } from './routes/food.seasons'
import { Route as FoodReportsRouteImport } from './routes/food.reports'
import { Route as FoodProcessingRouteImport } from './routes/food.processing'
import { Route as FoodPricesRouteImport } from './routes/food.prices'
import { Route as FoodPlanRouteImport } from './routes/food.plan'
import { Route as FoodOrchardRouteImport } from './routes/food.orchard'
import { Route as FoodLivestockRouteImport } from './routes/food.livestock'
import { Route as FoodGardenRouteImport } from './routes/food.garden'
import { Route as FoodCropsRouteImport } from './routes/food.crops'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminResetRouteImport } from './routes/admin.reset'

const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSchedulingRoute = ServiceSchedulingRouteImport.update({
  id: '/service-scheduling',
  path: '/service-scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodIndexRoute = FoodIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FoodRoute,
} as any)
const TasksScheduledRoute = TasksScheduledRouteImport.update({
  id: '/tasks/scheduled',
  path: '/tasks/scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksBacklogRoute = TasksBacklogRouteImport.update({
  id: '/tasks/backlog',
  path: '/tasks/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksSlugRoute = TasksSlugRouteImport.update({
  id: '/tasks/$slug',
  path: '/tasks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesDateRoute = NotesDateRouteImport.update({
  id: '/notes/$date',
  path: '/notes/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodStorageRoute = FoodStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => FoodRoute,
} as any)
const FoodSeasonsRoute = FoodSeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => FoodRoute,
} as any)
const FoodReportsRoute = FoodReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => FoodRoute,
} as any)
const FoodProcessingRoute = FoodProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => FoodRoute,
} as any)
const FoodPricesRoute = FoodPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => FoodRoute,
} as any)
const FoodPlanRoute = FoodPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => FoodRoute,
} as any)
const FoodOrchardRoute = FoodOrchardRouteImport.update({
  id: '/orchard',
  path: '/orchard',
  getParentRoute: () => FoodRoute,
} as any)
const FoodLivestockRoute = FoodLivestockRouteImport.update({
  id: '/livestock',
  path: '/livestock',
  getParentRoute: () => FoodRoute,
} as any)
const FoodGardenRoute = FoodGardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => FoodRoute,
} as any)
const FoodCropsRoute = FoodCropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => FoodRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetRoute = AdminResetRouteImport.update({
  id: '/admin/reset',
  path: '/admin/reset',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/food': typeof FoodRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/maintenance': typeof MaintenanceRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/service-scheduling': typeof ServiceSchedulingRoute
  '/sync': typeof SyncRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin/users': typeof AdminUsersRoute
  '/food/crops': typeof FoodCropsRoute
  '/food/garden': typeof FoodGardenRoute
  '/food/livestock': typeof FoodLivestockRoute
  '/food/orchard': typeof FoodOrchardRoute
  '/food/plan': typeof FoodPlanRoute
  '/food/prices': typeof FoodPricesRoute
  '/food/processing': typeof FoodProcessingRoute
  '/food/reports': typeof FoodReportsRoute
  '/food/seasons': typeof FoodSeasonsRoute
  '/food/storage': typeof FoodStorageRoute
  '/notes/$date': typeof NotesDateRoute
  '/tasks/$slug': typeof TasksSlugRoute
  '/tasks/backlog': typeof TasksBacklogRoute
  '/tasks/scheduled': typeof TasksScheduledRoute
  '/food/': typeof FoodIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/maintenance': typeof MaintenanceRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/service-scheduling': typeof ServiceSchedulingRoute
  '/sync': typeof SyncRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin/users': typeof AdminUsersRoute
  '/food/crops': typeof FoodCropsRoute
  '/food/garden': typeof FoodGardenRoute
  '/food/livestock': typeof FoodLivestockRoute
  '/food/orchard': typeof FoodOrchardRoute
  '/food/plan': typeof FoodPlanRoute
  '/food/prices': typeof FoodPricesRoute
  '/food/processing': typeof FoodProcessingRoute
  '/food/reports': typeof FoodReportsRoute
  '/food/seasons': typeof FoodSeasonsRoute
  '/food/storage': typeof FoodStorageRoute
  '/notes/$date': typeof NotesDateRoute
  '/tasks/$slug': typeof TasksSlugRoute
  '/tasks/backlog': typeof TasksBacklogRoute
  '/tasks/scheduled': typeof TasksScheduledRoute
  '/food': typeof FoodIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/food': typeof FoodRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/maintenance': typeof MaintenanceRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/service-scheduling': typeof ServiceSchedulingRoute
  '/sync': typeof SyncRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin/users': typeof AdminUsersRoute
  '/food/crops': typeof FoodCropsRoute
  '/food/garden': typeof FoodGardenRoute
  '/food/livestock': typeof FoodLivestockRoute
  '/food/orchard': typeof FoodOrchardRoute
  '/food/plan': typeof FoodPlanRoute
  '/food/prices': typeof FoodPricesRoute
  '/food/processing': typeof FoodProcessingRoute
  '/food/reports': typeof FoodReportsRoute
  '/food/seasons': typeof FoodSeasonsRoute
  '/food/storage': typeof FoodStorageRoute
  '/notes/$date': typeof NotesDateRoute
  '/tasks/$slug': typeof TasksSlugRoute
  '/tasks/backlog': typeof TasksBacklogRoute
  '/tasks/scheduled': typeof TasksScheduledRoute
  '/food/': typeof FoodIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/food'
    | '/inventory'
    | '/maintenance'
    | '/projects'
    | '/reports'
    | '/service-scheduling'
    | '/sync'
    | '/admin/reset'
    | '/admin/users'
    | '/food/crops'
    | '/food/garden'
    | '/food/livestock'
    | '/food/orchard'
    | '/food/plan'
    | '/food/prices'
    | '/food/processing'
    | '/food/reports'
    | '/food/seasons'
    | '/food/storage'
    | '/notes/$date'
    | '/tasks/$slug'
    | '/tasks/backlog'
    | '/tasks/scheduled'
    | '/food/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/inventory'
    | '/maintenance'
    | '/projects'
    | '/reports'
    | '/service-scheduling'
    | '/sync'
    | '/admin/reset'
    | '/admin/users'
    | '/food/crops'
    | '/food/garden'
    | '/food/livestock'
    | '/food/orchard'
    | '/food/plan'
    | '/food/prices'
    | '/food/processing'
    | '/food/reports'
    | '/food/seasons'
    | '/food/storage'
    | '/notes/$date'
    | '/tasks/$slug'
    | '/tasks/backlog'
    | '/tasks/scheduled'
    | '/food'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/food'
    | '/inventory'
    | '/maintenance'
    | '/projects'
    | '/reports'
    | '/service-scheduling'
    | '/sync'
    | '/admin/reset'
    | '/admin/users'
    | '/food/crops'
    | '/food/garden'
    | '/food/livestock'
    | '/food/orchard'
    | '/food/plan'
    | '/food/prices'
    | '/food/processing'
    | '/food/reports'
    | '/food/seasons'
    | '/food/storage'
    | '/notes/$date'
    | '/tasks/$slug'
    | '/tasks/backlog'
    | '/tasks/scheduled'
    | '/food/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  FoodRoute: typeof FoodRouteWithChildren
  InventoryRoute: typeof InventoryRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ProjectsRoute: typeof ProjectsRoute
  ReportsRoute: typeof ReportsRoute
  ServiceSchedulingRoute: typeof ServiceSchedulingRoute
  SyncRoute: typeof SyncRoute
  AdminResetRoute: typeof AdminResetRoute
  AdminUsersRoute: typeof AdminUsersRoute
  NotesDateRoute: typeof NotesDateRoute
  TasksSlugRoute: typeof TasksSlugRoute
  TasksBacklogRoute: typeof TasksBacklogRoute
  TasksScheduledRoute: typeof TasksScheduledRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-scheduling': {
      id: '/service-scheduling'
      path: '/service-scheduling'
      fullPath: '/service-scheduling'
      preLoaderRoute: typeof ServiceSchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/': {
      id: '/food/'
      path: '/'
      fullPath: '/food/'
      preLoaderRoute: typeof FoodIndexRouteImport
      parentRoute: typeof FoodRoute
    }
    '/tasks/scheduled': {
      id: '/tasks/scheduled'
      path: '/tasks/scheduled'
      fullPath: '/tasks/scheduled'
      preLoaderRoute: typeof TasksScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/backlog': {
      id: '/tasks/backlog'
      path: '/tasks/backlog'
      fullPath: '/tasks/backlog'
      preLoaderRoute: typeof TasksBacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$slug': {
      id: '/tasks/$slug'
      path: '/tasks/$slug'
      fullPath: '/tasks/$slug'
      preLoaderRoute: typeof TasksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$date': {
      id: '/notes/$date'
      path: '/notes/$date'
      fullPath: '/notes/$date'
      preLoaderRoute: typeof NotesDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/storage': {
      id: '/food/storage'
      path: '/storage'
      fullPath: '/food/storage'
      preLoaderRoute: typeof FoodStorageRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/seasons': {
      id: '/food/seasons'
      path: '/seasons'
      fullPath: '/food/seasons'
      preLoaderRoute: typeof FoodSeasonsRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/reports': {
      id: '/food/reports'
      path: '/reports'
      fullPath: '/food/reports'
      preLoaderRoute: typeof FoodReportsRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/processing': {
      id: '/food/processing'
      path: '/processing'
      fullPath: '/food/processing'
      preLoaderRoute: typeof FoodProcessingRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/prices': {
      id: '/food/prices'
      path: '/prices'
      fullPath: '/food/prices'
      preLoaderRoute: typeof FoodPricesRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/plan': {
      id: '/food/plan'
      path: '/plan'
      fullPath: '/food/plan'
      preLoaderRoute: typeof FoodPlanRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/orchard': {
      id: '/food/orchard'
      path: '/orchard'
      fullPath: '/food/orchard'
      preLoaderRoute: typeof FoodOrchardRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/livestock': {
      id: '/food/livestock'
      path: '/livestock'
      fullPath: '/food/livestock'
      preLoaderRoute: typeof FoodLivestockRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/garden': {
      id: '/food/garden'
      path: '/garden'
      fullPath: '/food/garden'
      preLoaderRoute: typeof FoodGardenRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/crops': {
      id: '/food/crops'
      path: '/crops'
      fullPath: '/food/crops'
      preLoaderRoute: typeof FoodCropsRouteImport
      parentRoute: typeof FoodRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset': {
      id: '/admin/reset'
      path: '/admin/reset'
      fullPath: '/admin/reset'
      preLoaderRoute: typeof AdminResetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FoodRouteChildren {
  FoodCropsRoute: typeof FoodCropsRoute
  FoodGardenRoute: typeof FoodGardenRoute
  FoodLivestockRoute: typeof FoodLivestockRoute
  FoodOrchardRoute: typeof FoodOrchardRoute
  FoodPlanRoute: typeof FoodPlanRoute
  FoodPricesRoute: typeof FoodPricesRoute
  FoodProcessingRoute: typeof FoodProcessingRoute
  FoodReportsRoute: typeof FoodReportsRoute
  FoodSeasonsRoute: typeof FoodSeasonsRoute
  FoodStorageRoute: typeof FoodStorageRoute
  FoodIndexRoute: typeof FoodIndexRoute
}

const FoodRouteChildren: FoodRouteChildren = {
  FoodCropsRoute: FoodCropsRoute,
  FoodGardenRoute: FoodGardenRoute,
  FoodLivestockRoute: FoodLivestockRoute,
  FoodOrchardRoute: FoodOrchardRoute,
  FoodPlanRoute: FoodPlanRoute,
  FoodPricesRoute: FoodPricesRoute,
  FoodProcessingRoute: FoodProcessingRoute,
  FoodReportsRoute: FoodReportsRoute,
  FoodSeasonsRoute: FoodSeasonsRoute,
  FoodStorageRoute: FoodStorageRoute,
  FoodIndexRoute: FoodIndexRoute,
}

const FoodRouteWithChildren = FoodRoute._addFileChildren(FoodRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  FoodRoute: FoodRouteWithChildren,
  InventoryRoute: InventoryRoute,
  MaintenanceRoute: MaintenanceRoute,
  ProjectsRoute: ProjectsRoute,
  ReportsRoute: ReportsRoute,
  ServiceSchedulingRoute: ServiceSchedulingRoute,
  SyncRoute: SyncRoute,
  AdminResetRoute: AdminResetRoute,
  AdminUsersRoute: AdminUsersRoute,
  NotesDateRoute: NotesDateRoute,
  TasksSlugRoute: TasksSlugRoute,
  TasksBacklogRoute: TasksBacklogRoute,
  TasksScheduledRoute: TasksScheduledRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
