/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as ServiceSchedulingRouteImport } from './routes/service-scheduling'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReadyRouteImport } from './routes/ready'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProceduresRouteImport } from './routes/procedures'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FoodRouteImport } from './routes/food'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as ProceduresIndexRouteImport } from './routes/procedures.index'
import { Route as MaintenanceIndexRouteImport } from './routes/maintenance.index'
import { Route as FoodIndexRouteImport } from './routes/food.index'
import { Route as ElectricalIndexRouteImport } from './routes/electrical.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TasksScheduledRouteImport } from './routes/tasks.scheduled'
import { Route as TasksRefsRouteImport } from './routes/tasks.refs'
import { Route as TasksBacklogRouteImport } from './routes/tasks.backlog'
import { Route as TasksSlugRouteImport } from './routes/tasks.$slug'
import { Route as SettingsTroubleshootingRouteImport } from './routes/settings.troubleshooting'
import { Route as SettingsSelfHostRouteImport } from './routes/settings.self-host'
import { Route as ProceduresIngestRouteImport } from './routes/procedures.ingest'
import { Route as NotesDateRouteImport } from './routes/notes.$date'
import { Route as MaintenanceImportManualRouteImport } from './routes/maintenance.import-manual'
import { Route as MaintenanceGenerateScheduleRouteImport } from './routes/maintenance.generate-schedule'
import { Route as MaintenanceForecastRouteImport } from './routes/maintenance.forecast'
import { Route as MaintenanceDiagnoseRouteImport } from './routes/maintenance.diagnose'
import { Route as HealthSchemaRouteImport } from './routes/health.schema'
import { Route as FoodStorageRouteImport } from './routes/food.storage'
import { Route as FoodSeasonsRouteImport } from './routes/food.seasons'
import { Route as FoodReportsRouteImport } from './routes/food.reports'
import { Route as FoodProcessingRouteImport } from './routes/food.processing'
import { Route as FoodPricesRouteImport } from './routes/food.prices'
import { Route as FoodPreserveRouteImport } from './routes/food.preserve'
import { Route as FoodPlanRouteImport } from './routes/food.plan'
import { Route as FoodOrchardRouteImport } from './routes/food.orchard'
import { Route as FoodLivestockRouteImport } from './routes/food.livestock'
import { Route as FoodIrrigationRouteImport } from './routes/food.irrigation'
import { Route as FoodGardenRouteImport } from './routes/food.garden'
import { Route as FoodCropsRouteImport } from './routes/food.crops'
import { Route as ElectricalStandardsRouteImport } from './routes/electrical.standards'
import { Route as ElectricalSorRouteImport } from './routes/electrical.sor'
import { Route as ElectricalQaRouteImport } from './routes/electrical.qa'
import { Route as ElectricalImportRouteImport } from './routes/electrical.import'
import { Route as ElectricalExportRouteImport } from './routes/electrical.export'
import { Route as ElectricalDiagramsRouteImport } from './routes/electrical.diagrams'
import { Route as ElectricalKindRouteImport } from './routes/electrical.$kind'
import { Route as AdminVaultSecretsRouteImport } from './routes/admin.vault-secrets'
import { Route as AdminVaultRotationRouteImport } from './routes/admin.vault-rotation'
import { Route as AdminVaultBackupRouteImport } from './routes/admin.vault-backup'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTaskHealthRouteImport } from './routes/admin.task-health'
import { Route as AdminTaskDedupeRouteImport } from './routes/admin.task-dedupe'
import { Route as AdminSchemaRouteImport } from './routes/admin.schema'
import { Route as AdminRestoreRouteImport } from './routes/admin.restore'
import { Route as AdminResetRouteImport } from './routes/admin.reset'
import { Route as AdminExportKeyRouteImport } from './routes/admin.export-key'
import { Route as AdminExportRouteImport } from './routes/admin.export'
import { Route as AdminAiSettingsRouteImport } from './routes/admin.ai-settings'
import { Route as AdminAiEnginesRouteImport } from './routes/admin.ai-engines'
import { Route as AdminAddonsRouteImport } from './routes/admin.addons'
import { Route as ApiPublicReadyRouteImport } from './routes/api/public/ready'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiElectricalSnapshotRouteImport } from './routes/api/electrical/snapshot'
import { Route as ElectricalItemKindIdRouteImport } from './routes/electrical.item.$kind.$id'
import { Route as ApiPublicWebhooksRachioRouteImport } from './routes/api/public/webhooks/rachio'
import { Route as ApiPublicHooksTaskHealthRouteImport } from './routes/api/public/hooks/task-health'
import { Route as ApiPublicHooksRachioSyncRouteImport } from './routes/api/public/hooks/rachio-sync'
import { Route as ApiPublicHealthProceduresRouteImport } from './routes/api/public/health.procedures'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSchedulingRoute = ServiceSchedulingRouteImport.update({
  id: '/service-scheduling',
  path: '/service-scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyRoute = ReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProceduresRoute = ProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProceduresIndexRoute = ProceduresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProceduresRoute,
} as any)
const MaintenanceIndexRoute = MaintenanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MaintenanceRoute,
} as any)
const FoodIndexRoute = FoodIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FoodRoute,
} as any)
const ElectricalIndexRoute = ElectricalIndexRouteImport.update({
  id: '/electrical/',
  path: '/electrical/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksScheduledRoute = TasksScheduledRouteImport.update({
  id: '/tasks/scheduled',
  path: '/tasks/scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRefsRoute = TasksRefsRouteImport.update({
  id: '/tasks/refs',
  path: '/tasks/refs',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksBacklogRoute = TasksBacklogRouteImport.update({
  id: '/tasks/backlog',
  path: '/tasks/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksSlugRoute = TasksSlugRouteImport.update({
  id: '/tasks/$slug',
  path: '/tasks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTroubleshootingRoute = SettingsTroubleshootingRouteImport.update({
  id: '/settings/troubleshooting',
  path: '/settings/troubleshooting',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSelfHostRoute = SettingsSelfHostRouteImport.update({
  id: '/settings/self-host',
  path: '/settings/self-host',
  getParentRoute: () => rootRouteImport,
} as any)
const ProceduresIngestRoute = ProceduresIngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => ProceduresRoute,
} as any)
const NotesDateRoute = NotesDateRouteImport.update({
  id: '/notes/$date',
  path: '/notes/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceImportManualRoute = MaintenanceImportManualRouteImport.update({
  id: '/import-manual',
  path: '/import-manual',
  getParentRoute: () => MaintenanceRoute,
} as any)
const MaintenanceGenerateScheduleRoute =
  MaintenanceGenerateScheduleRouteImport.update({
    id: '/generate-schedule',
    path: '/generate-schedule',
    getParentRoute: () => MaintenanceRoute,
  } as any)
const MaintenanceForecastRoute = MaintenanceForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => MaintenanceRoute,
} as any)
const MaintenanceDiagnoseRoute = MaintenanceDiagnoseRouteImport.update({
  id: '/diagnose',
  path: '/diagnose',
  getParentRoute: () => MaintenanceRoute,
} as any)
const HealthSchemaRoute = HealthSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => HealthRoute,
} as any)
const FoodStorageRoute = FoodStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => FoodRoute,
} as any)
const FoodSeasonsRoute = FoodSeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => FoodRoute,
} as any)
const FoodReportsRoute = FoodReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => FoodRoute,
} as any)
const FoodProcessingRoute = FoodProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => FoodRoute,
} as any)
const FoodPricesRoute = FoodPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => FoodRoute,
} as any)
const FoodPreserveRoute = FoodPreserveRouteImport.update({
  id: '/preserve',
  path: '/preserve',
  getParentRoute: () => FoodRoute,
} as any)
const FoodPlanRoute = FoodPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => FoodRoute,
} as any)
const FoodOrchardRoute = FoodOrchardRouteImport.update({
  id: '/orchard',
  path: '/orchard',
  getParentRoute: () => FoodRoute,
} as any)
const FoodLivestockRoute = FoodLivestockRouteImport.update({
  id: '/livestock',
  path: '/livestock',
  getParentRoute: () => FoodRoute,
} as any)
const FoodIrrigationRoute = FoodIrrigationRouteImport.update({
  id: '/irrigation',
  path: '/irrigation',
  getParentRoute: () => FoodRoute,
} as any)
const FoodGardenRoute = FoodGardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => FoodRoute,
} as any)
const FoodCropsRoute = FoodCropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => FoodRoute,
} as any)
const ElectricalStandardsRoute = ElectricalStandardsRouteImport.update({
  id: '/electrical/standards',
  path: '/electrical/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricalSorRoute = ElectricalSorRouteImport.update({
  id: '/electrical/sor',
  path: '/electrical/sor',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricalQaRoute = ElectricalQaRouteImport.update({
  id: '/electrical/qa',
  path: '/electrical/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricalImportRoute = ElectricalImportRouteImport.update({
  id: '/electrical/import',
  path: '/electrical/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricalExportRoute = ElectricalExportRouteImport.update({
  id: '/electrical/export',
  path: '/electrical/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricalDiagramsRoute = ElectricalDiagramsRouteImport.update({
  id: '/electrical/diagrams',
  path: '/electrical/diagrams',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricalKindRoute = ElectricalKindRouteImport.update({
  id: '/electrical/$kind',
  path: '/electrical/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVaultSecretsRoute = AdminVaultSecretsRouteImport.update({
  id: '/admin/vault-secrets',
  path: '/admin/vault-secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVaultRotationRoute = AdminVaultRotationRouteImport.update({
  id: '/admin/vault-rotation',
  path: '/admin/vault-rotation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVaultBackupRoute = AdminVaultBackupRouteImport.update({
  id: '/admin/vault-backup',
  path: '/admin/vault-backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTaskHealthRoute = AdminTaskHealthRouteImport.update({
  id: '/admin/task-health',
  path: '/admin/task-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTaskDedupeRoute = AdminTaskDedupeRouteImport.update({
  id: '/admin/task-dedupe',
  path: '/admin/task-dedupe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSchemaRoute = AdminSchemaRouteImport.update({
  id: '/admin/schema',
  path: '/admin/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRestoreRoute = AdminRestoreRouteImport.update({
  id: '/admin/restore',
  path: '/admin/restore',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetRoute = AdminResetRouteImport.update({
  id: '/admin/reset',
  path: '/admin/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExportKeyRoute = AdminExportKeyRouteImport.update({
  id: '/admin/export-key',
  path: '/admin/export-key',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/admin/export',
  path: '/admin/export',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiSettingsRoute = AdminAiSettingsRouteImport.update({
  id: '/admin/ai-settings',
  path: '/admin/ai-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiEnginesRoute = AdminAiEnginesRouteImport.update({
  id: '/admin/ai-engines',
  path: '/admin/ai-engines',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAddonsRoute = AdminAddonsRouteImport.update({
  id: '/admin/addons',
  path: '/admin/addons',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReadyRoute = ApiPublicReadyRouteImport.update({
  id: '/api/public/ready',
  path: '/api/public/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectricalSnapshotRoute = ApiElectricalSnapshotRouteImport.update({
  id: '/api/electrical/snapshot',
  path: '/api/electrical/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricalItemKindIdRoute = ElectricalItemKindIdRouteImport.update({
  id: '/electrical/item/$kind/$id',
  path: '/electrical/item/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksRachioRoute = ApiPublicWebhooksRachioRouteImport.update({
  id: '/api/public/webhooks/rachio',
  path: '/api/public/webhooks/rachio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTaskHealthRoute =
  ApiPublicHooksTaskHealthRouteImport.update({
    id: '/api/public/hooks/task-health',
    path: '/api/public/hooks/task-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRachioSyncRoute =
  ApiPublicHooksRachioSyncRouteImport.update({
    id: '/api/public/hooks/rachio-sync',
    path: '/api/public/hooks/rachio-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHealthProceduresRoute =
  ApiPublicHealthProceduresRouteImport.update({
    id: '/procedures',
    path: '/procedures',
    getParentRoute: () => ApiPublicHealthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/deck': typeof DeckRoute
  '/food': typeof FoodRouteWithChildren
  '/health': typeof HealthRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/maintenance': typeof MaintenanceRouteWithChildren
  '/procedures': typeof ProceduresRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/ready': typeof ReadyRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-scheduling': typeof ServiceSchedulingRoute
  '/sync': typeof SyncRoute
  '/vault': typeof VaultRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/ai-engines': typeof AdminAiEnginesRoute
  '/admin/ai-settings': typeof AdminAiSettingsRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/export-key': typeof AdminExportKeyRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin/restore': typeof AdminRestoreRoute
  '/admin/schema': typeof AdminSchemaRoute
  '/admin/task-dedupe': typeof AdminTaskDedupeRoute
  '/admin/task-health': typeof AdminTaskHealthRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vault-backup': typeof AdminVaultBackupRoute
  '/admin/vault-rotation': typeof AdminVaultRotationRoute
  '/admin/vault-secrets': typeof AdminVaultSecretsRoute
  '/electrical/$kind': typeof ElectricalKindRoute
  '/electrical/diagrams': typeof ElectricalDiagramsRoute
  '/electrical/export': typeof ElectricalExportRoute
  '/electrical/import': typeof ElectricalImportRoute
  '/electrical/qa': typeof ElectricalQaRoute
  '/electrical/sor': typeof ElectricalSorRoute
  '/electrical/standards': typeof ElectricalStandardsRoute
  '/food/crops': typeof FoodCropsRoute
  '/food/garden': typeof FoodGardenRoute
  '/food/irrigation': typeof FoodIrrigationRoute
  '/food/livestock': typeof FoodLivestockRoute
  '/food/orchard': typeof FoodOrchardRoute
  '/food/plan': typeof FoodPlanRoute
  '/food/preserve': typeof FoodPreserveRoute
  '/food/prices': typeof FoodPricesRoute
  '/food/processing': typeof FoodProcessingRoute
  '/food/reports': typeof FoodReportsRoute
  '/food/seasons': typeof FoodSeasonsRoute
  '/food/storage': typeof FoodStorageRoute
  '/health/schema': typeof HealthSchemaRoute
  '/maintenance/diagnose': typeof MaintenanceDiagnoseRoute
  '/maintenance/forecast': typeof MaintenanceForecastRoute
  '/maintenance/generate-schedule': typeof MaintenanceGenerateScheduleRoute
  '/maintenance/import-manual': typeof MaintenanceImportManualRoute
  '/notes/$date': typeof NotesDateRoute
  '/procedures/ingest': typeof ProceduresIngestRoute
  '/settings/self-host': typeof SettingsSelfHostRoute
  '/settings/troubleshooting': typeof SettingsTroubleshootingRoute
  '/tasks/$slug': typeof TasksSlugRoute
  '/tasks/backlog': typeof TasksBacklogRoute
  '/tasks/refs': typeof TasksRefsRoute
  '/tasks/scheduled': typeof TasksScheduledRoute
  '/admin/': typeof AdminIndexRoute
  '/electrical/': typeof ElectricalIndexRoute
  '/food/': typeof FoodIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/procedures/': typeof ProceduresIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/electrical/snapshot': typeof ApiElectricalSnapshotRoute
  '/api/public/health': typeof ApiPublicHealthRouteWithChildren
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/api/public/health/procedures': typeof ApiPublicHealthProceduresRoute
  '/api/public/hooks/rachio-sync': typeof ApiPublicHooksRachioSyncRoute
  '/api/public/hooks/task-health': typeof ApiPublicHooksTaskHealthRoute
  '/api/public/webhooks/rachio': typeof ApiPublicWebhooksRachioRoute
  '/electrical/item/$kind/$id': typeof ElectricalItemKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/deck': typeof DeckRoute
  '/health': typeof HealthRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/projects': typeof ProjectsRoute
  '/ready': typeof ReadyRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-scheduling': typeof ServiceSchedulingRoute
  '/sync': typeof SyncRoute
  '/vault': typeof VaultRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/ai-engines': typeof AdminAiEnginesRoute
  '/admin/ai-settings': typeof AdminAiSettingsRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/export-key': typeof AdminExportKeyRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin/restore': typeof AdminRestoreRoute
  '/admin/schema': typeof AdminSchemaRoute
  '/admin/task-dedupe': typeof AdminTaskDedupeRoute
  '/admin/task-health': typeof AdminTaskHealthRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vault-backup': typeof AdminVaultBackupRoute
  '/admin/vault-rotation': typeof AdminVaultRotationRoute
  '/admin/vault-secrets': typeof AdminVaultSecretsRoute
  '/electrical/$kind': typeof ElectricalKindRoute
  '/electrical/diagrams': typeof ElectricalDiagramsRoute
  '/electrical/export': typeof ElectricalExportRoute
  '/electrical/import': typeof ElectricalImportRoute
  '/electrical/qa': typeof ElectricalQaRoute
  '/electrical/sor': typeof ElectricalSorRoute
  '/electrical/standards': typeof ElectricalStandardsRoute
  '/food/crops': typeof FoodCropsRoute
  '/food/garden': typeof FoodGardenRoute
  '/food/irrigation': typeof FoodIrrigationRoute
  '/food/livestock': typeof FoodLivestockRoute
  '/food/orchard': typeof FoodOrchardRoute
  '/food/plan': typeof FoodPlanRoute
  '/food/preserve': typeof FoodPreserveRoute
  '/food/prices': typeof FoodPricesRoute
  '/food/processing': typeof FoodProcessingRoute
  '/food/reports': typeof FoodReportsRoute
  '/food/seasons': typeof FoodSeasonsRoute
  '/food/storage': typeof FoodStorageRoute
  '/health/schema': typeof HealthSchemaRoute
  '/maintenance/diagnose': typeof MaintenanceDiagnoseRoute
  '/maintenance/forecast': typeof MaintenanceForecastRoute
  '/maintenance/generate-schedule': typeof MaintenanceGenerateScheduleRoute
  '/maintenance/import-manual': typeof MaintenanceImportManualRoute
  '/notes/$date': typeof NotesDateRoute
  '/procedures/ingest': typeof ProceduresIngestRoute
  '/settings/self-host': typeof SettingsSelfHostRoute
  '/settings/troubleshooting': typeof SettingsTroubleshootingRoute
  '/tasks/$slug': typeof TasksSlugRoute
  '/tasks/backlog': typeof TasksBacklogRoute
  '/tasks/refs': typeof TasksRefsRoute
  '/tasks/scheduled': typeof TasksScheduledRoute
  '/admin': typeof AdminIndexRoute
  '/electrical': typeof ElectricalIndexRoute
  '/food': typeof FoodIndexRoute
  '/maintenance': typeof MaintenanceIndexRoute
  '/procedures': typeof ProceduresIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/api/electrical/snapshot': typeof ApiElectricalSnapshotRoute
  '/api/public/health': typeof ApiPublicHealthRouteWithChildren
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/api/public/health/procedures': typeof ApiPublicHealthProceduresRoute
  '/api/public/hooks/rachio-sync': typeof ApiPublicHooksRachioSyncRoute
  '/api/public/hooks/task-health': typeof ApiPublicHooksTaskHealthRoute
  '/api/public/webhooks/rachio': typeof ApiPublicWebhooksRachioRoute
  '/electrical/item/$kind/$id': typeof ElectricalItemKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/deck': typeof DeckRoute
  '/food': typeof FoodRouteWithChildren
  '/health': typeof HealthRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/maintenance': typeof MaintenanceRouteWithChildren
  '/procedures': typeof ProceduresRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/ready': typeof ReadyRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-scheduling': typeof ServiceSchedulingRoute
  '/sync': typeof SyncRoute
  '/vault': typeof VaultRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/ai-engines': typeof AdminAiEnginesRoute
  '/admin/ai-settings': typeof AdminAiSettingsRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/export-key': typeof AdminExportKeyRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin/restore': typeof AdminRestoreRoute
  '/admin/schema': typeof AdminSchemaRoute
  '/admin/task-dedupe': typeof AdminTaskDedupeRoute
  '/admin/task-health': typeof AdminTaskHealthRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vault-backup': typeof AdminVaultBackupRoute
  '/admin/vault-rotation': typeof AdminVaultRotationRoute
  '/admin/vault-secrets': typeof AdminVaultSecretsRoute
  '/electrical/$kind': typeof ElectricalKindRoute
  '/electrical/diagrams': typeof ElectricalDiagramsRoute
  '/electrical/export': typeof ElectricalExportRoute
  '/electrical/import': typeof ElectricalImportRoute
  '/electrical/qa': typeof ElectricalQaRoute
  '/electrical/sor': typeof ElectricalSorRoute
  '/electrical/standards': typeof ElectricalStandardsRoute
  '/food/crops': typeof FoodCropsRoute
  '/food/garden': typeof FoodGardenRoute
  '/food/irrigation': typeof FoodIrrigationRoute
  '/food/livestock': typeof FoodLivestockRoute
  '/food/orchard': typeof FoodOrchardRoute
  '/food/plan': typeof FoodPlanRoute
  '/food/preserve': typeof FoodPreserveRoute
  '/food/prices': typeof FoodPricesRoute
  '/food/processing': typeof FoodProcessingRoute
  '/food/reports': typeof FoodReportsRoute
  '/food/seasons': typeof FoodSeasonsRoute
  '/food/storage': typeof FoodStorageRoute
  '/health/schema': typeof HealthSchemaRoute
  '/maintenance/diagnose': typeof MaintenanceDiagnoseRoute
  '/maintenance/forecast': typeof MaintenanceForecastRoute
  '/maintenance/generate-schedule': typeof MaintenanceGenerateScheduleRoute
  '/maintenance/import-manual': typeof MaintenanceImportManualRoute
  '/notes/$date': typeof NotesDateRoute
  '/procedures/ingest': typeof ProceduresIngestRoute
  '/settings/self-host': typeof SettingsSelfHostRoute
  '/settings/troubleshooting': typeof SettingsTroubleshootingRoute
  '/tasks/$slug': typeof TasksSlugRoute
  '/tasks/backlog': typeof TasksBacklogRoute
  '/tasks/refs': typeof TasksRefsRoute
  '/tasks/scheduled': typeof TasksScheduledRoute
  '/admin/': typeof AdminIndexRoute
  '/electrical/': typeof ElectricalIndexRoute
  '/food/': typeof FoodIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/procedures/': typeof ProceduresIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/electrical/snapshot': typeof ApiElectricalSnapshotRoute
  '/api/public/health': typeof ApiPublicHealthRouteWithChildren
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/api/public/health/procedures': typeof ApiPublicHealthProceduresRoute
  '/api/public/hooks/rachio-sync': typeof ApiPublicHooksRachioSyncRoute
  '/api/public/hooks/task-health': typeof ApiPublicHooksTaskHealthRoute
  '/api/public/webhooks/rachio': typeof ApiPublicWebhooksRachioRoute
  '/electrical/item/$kind/$id': typeof ElectricalItemKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/deck'
    | '/food'
    | '/health'
    | '/inventory'
    | '/maintenance'
    | '/procedures'
    | '/projects'
    | '/ready'
    | '/reports'
    | '/reset-password'
    | '/service-scheduling'
    | '/sync'
    | '/vault'
    | '/admin/addons'
    | '/admin/ai-engines'
    | '/admin/ai-settings'
    | '/admin/export'
    | '/admin/export-key'
    | '/admin/reset'
    | '/admin/restore'
    | '/admin/schema'
    | '/admin/task-dedupe'
    | '/admin/task-health'
    | '/admin/users'
    | '/admin/vault-backup'
    | '/admin/vault-rotation'
    | '/admin/vault-secrets'
    | '/electrical/$kind'
    | '/electrical/diagrams'
    | '/electrical/export'
    | '/electrical/import'
    | '/electrical/qa'
    | '/electrical/sor'
    | '/electrical/standards'
    | '/food/crops'
    | '/food/garden'
    | '/food/irrigation'
    | '/food/livestock'
    | '/food/orchard'
    | '/food/plan'
    | '/food/preserve'
    | '/food/prices'
    | '/food/processing'
    | '/food/reports'
    | '/food/seasons'
    | '/food/storage'
    | '/health/schema'
    | '/maintenance/diagnose'
    | '/maintenance/forecast'
    | '/maintenance/generate-schedule'
    | '/maintenance/import-manual'
    | '/notes/$date'
    | '/procedures/ingest'
    | '/settings/self-host'
    | '/settings/troubleshooting'
    | '/tasks/$slug'
    | '/tasks/backlog'
    | '/tasks/refs'
    | '/tasks/scheduled'
    | '/admin/'
    | '/electrical/'
    | '/food/'
    | '/maintenance/'
    | '/procedures/'
    | '/tasks/'
    | '/api/electrical/snapshot'
    | '/api/public/health'
    | '/api/public/ready'
    | '/api/public/health/procedures'
    | '/api/public/hooks/rachio-sync'
    | '/api/public/hooks/task-health'
    | '/api/public/webhooks/rachio'
    | '/electrical/item/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/deck'
    | '/health'
    | '/inventory'
    | '/projects'
    | '/ready'
    | '/reports'
    | '/reset-password'
    | '/service-scheduling'
    | '/sync'
    | '/vault'
    | '/admin/addons'
    | '/admin/ai-engines'
    | '/admin/ai-settings'
    | '/admin/export'
    | '/admin/export-key'
    | '/admin/reset'
    | '/admin/restore'
    | '/admin/schema'
    | '/admin/task-dedupe'
    | '/admin/task-health'
    | '/admin/users'
    | '/admin/vault-backup'
    | '/admin/vault-rotation'
    | '/admin/vault-secrets'
    | '/electrical/$kind'
    | '/electrical/diagrams'
    | '/electrical/export'
    | '/electrical/import'
    | '/electrical/qa'
    | '/electrical/sor'
    | '/electrical/standards'
    | '/food/crops'
    | '/food/garden'
    | '/food/irrigation'
    | '/food/livestock'
    | '/food/orchard'
    | '/food/plan'
    | '/food/preserve'
    | '/food/prices'
    | '/food/processing'
    | '/food/reports'
    | '/food/seasons'
    | '/food/storage'
    | '/health/schema'
    | '/maintenance/diagnose'
    | '/maintenance/forecast'
    | '/maintenance/generate-schedule'
    | '/maintenance/import-manual'
    | '/notes/$date'
    | '/procedures/ingest'
    | '/settings/self-host'
    | '/settings/troubleshooting'
    | '/tasks/$slug'
    | '/tasks/backlog'
    | '/tasks/refs'
    | '/tasks/scheduled'
    | '/admin'
    | '/electrical'
    | '/food'
    | '/maintenance'
    | '/procedures'
    | '/tasks'
    | '/api/electrical/snapshot'
    | '/api/public/health'
    | '/api/public/ready'
    | '/api/public/health/procedures'
    | '/api/public/hooks/rachio-sync'
    | '/api/public/hooks/task-health'
    | '/api/public/webhooks/rachio'
    | '/electrical/item/$kind/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/deck'
    | '/food'
    | '/health'
    | '/inventory'
    | '/maintenance'
    | '/procedures'
    | '/projects'
    | '/ready'
    | '/reports'
    | '/reset-password'
    | '/service-scheduling'
    | '/sync'
    | '/vault'
    | '/admin/addons'
    | '/admin/ai-engines'
    | '/admin/ai-settings'
    | '/admin/export'
    | '/admin/export-key'
    | '/admin/reset'
    | '/admin/restore'
    | '/admin/schema'
    | '/admin/task-dedupe'
    | '/admin/task-health'
    | '/admin/users'
    | '/admin/vault-backup'
    | '/admin/vault-rotation'
    | '/admin/vault-secrets'
    | '/electrical/$kind'
    | '/electrical/diagrams'
    | '/electrical/export'
    | '/electrical/import'
    | '/electrical/qa'
    | '/electrical/sor'
    | '/electrical/standards'
    | '/food/crops'
    | '/food/garden'
    | '/food/irrigation'
    | '/food/livestock'
    | '/food/orchard'
    | '/food/plan'
    | '/food/preserve'
    | '/food/prices'
    | '/food/processing'
    | '/food/reports'
    | '/food/seasons'
    | '/food/storage'
    | '/health/schema'
    | '/maintenance/diagnose'
    | '/maintenance/forecast'
    | '/maintenance/generate-schedule'
    | '/maintenance/import-manual'
    | '/notes/$date'
    | '/procedures/ingest'
    | '/settings/self-host'
    | '/settings/troubleshooting'
    | '/tasks/$slug'
    | '/tasks/backlog'
    | '/tasks/refs'
    | '/tasks/scheduled'
    | '/admin/'
    | '/electrical/'
    | '/food/'
    | '/maintenance/'
    | '/procedures/'
    | '/tasks/'
    | '/api/electrical/snapshot'
    | '/api/public/health'
    | '/api/public/ready'
    | '/api/public/health/procedures'
    | '/api/public/hooks/rachio-sync'
    | '/api/public/hooks/task-health'
    | '/api/public/webhooks/rachio'
    | '/electrical/item/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DeckRoute: typeof DeckRoute
  FoodRoute: typeof FoodRouteWithChildren
  HealthRoute: typeof HealthRouteWithChildren
  InventoryRoute: typeof InventoryRoute
  MaintenanceRoute: typeof MaintenanceRouteWithChildren
  ProceduresRoute: typeof ProceduresRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  ReadyRoute: typeof ReadyRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServiceSchedulingRoute: typeof ServiceSchedulingRoute
  SyncRoute: typeof SyncRoute
  VaultRoute: typeof VaultRoute
  AdminAddonsRoute: typeof AdminAddonsRoute
  AdminAiEnginesRoute: typeof AdminAiEnginesRoute
  AdminAiSettingsRoute: typeof AdminAiSettingsRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminExportKeyRoute: typeof AdminExportKeyRoute
  AdminResetRoute: typeof AdminResetRoute
  AdminRestoreRoute: typeof AdminRestoreRoute
  AdminSchemaRoute: typeof AdminSchemaRoute
  AdminTaskDedupeRoute: typeof AdminTaskDedupeRoute
  AdminTaskHealthRoute: typeof AdminTaskHealthRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVaultBackupRoute: typeof AdminVaultBackupRoute
  AdminVaultRotationRoute: typeof AdminVaultRotationRoute
  AdminVaultSecretsRoute: typeof AdminVaultSecretsRoute
  ElectricalKindRoute: typeof ElectricalKindRoute
  ElectricalDiagramsRoute: typeof ElectricalDiagramsRoute
  ElectricalExportRoute: typeof ElectricalExportRoute
  ElectricalImportRoute: typeof ElectricalImportRoute
  ElectricalQaRoute: typeof ElectricalQaRoute
  ElectricalSorRoute: typeof ElectricalSorRoute
  ElectricalStandardsRoute: typeof ElectricalStandardsRoute
  NotesDateRoute: typeof NotesDateRoute
  SettingsSelfHostRoute: typeof SettingsSelfHostRoute
  SettingsTroubleshootingRoute: typeof SettingsTroubleshootingRoute
  TasksSlugRoute: typeof TasksSlugRoute
  TasksBacklogRoute: typeof TasksBacklogRoute
  TasksRefsRoute: typeof TasksRefsRoute
  TasksScheduledRoute: typeof TasksScheduledRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ElectricalIndexRoute: typeof ElectricalIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  ApiElectricalSnapshotRoute: typeof ApiElectricalSnapshotRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRouteWithChildren
  ApiPublicReadyRoute: typeof ApiPublicReadyRoute
  ApiPublicHooksRachioSyncRoute: typeof ApiPublicHooksRachioSyncRoute
  ApiPublicHooksTaskHealthRoute: typeof ApiPublicHooksTaskHealthRoute
  ApiPublicWebhooksRachioRoute: typeof ApiPublicWebhooksRachioRoute
  ElectricalItemKindIdRoute: typeof ElectricalItemKindIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-scheduling': {
      id: '/service-scheduling'
      path: '/service-scheduling'
      fullPath: '/service-scheduling'
      preLoaderRoute: typeof ServiceSchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready': {
      id: '/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedures': {
      id: '/procedures'
      path: '/procedures'
      fullPath: '/procedures'
      preLoaderRoute: typeof ProceduresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedures/': {
      id: '/procedures/'
      path: '/'
      fullPath: '/procedures/'
      preLoaderRoute: typeof ProceduresIndexRouteImport
      parentRoute: typeof ProceduresRoute
    }
    '/maintenance/': {
      id: '/maintenance/'
      path: '/'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof MaintenanceIndexRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/food/': {
      id: '/food/'
      path: '/'
      fullPath: '/food/'
      preLoaderRoute: typeof FoodIndexRouteImport
      parentRoute: typeof FoodRoute
    }
    '/electrical/': {
      id: '/electrical/'
      path: '/electrical'
      fullPath: '/electrical/'
      preLoaderRoute: typeof ElectricalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/scheduled': {
      id: '/tasks/scheduled'
      path: '/tasks/scheduled'
      fullPath: '/tasks/scheduled'
      preLoaderRoute: typeof TasksScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/refs': {
      id: '/tasks/refs'
      path: '/tasks/refs'
      fullPath: '/tasks/refs'
      preLoaderRoute: typeof TasksRefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/backlog': {
      id: '/tasks/backlog'
      path: '/tasks/backlog'
      fullPath: '/tasks/backlog'
      preLoaderRoute: typeof TasksBacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$slug': {
      id: '/tasks/$slug'
      path: '/tasks/$slug'
      fullPath: '/tasks/$slug'
      preLoaderRoute: typeof TasksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/troubleshooting': {
      id: '/settings/troubleshooting'
      path: '/settings/troubleshooting'
      fullPath: '/settings/troubleshooting'
      preLoaderRoute: typeof SettingsTroubleshootingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/self-host': {
      id: '/settings/self-host'
      path: '/settings/self-host'
      fullPath: '/settings/self-host'
      preLoaderRoute: typeof SettingsSelfHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedures/ingest': {
      id: '/procedures/ingest'
      path: '/ingest'
      fullPath: '/procedures/ingest'
      preLoaderRoute: typeof ProceduresIngestRouteImport
      parentRoute: typeof ProceduresRoute
    }
    '/notes/$date': {
      id: '/notes/$date'
      path: '/notes/$date'
      fullPath: '/notes/$date'
      preLoaderRoute: typeof NotesDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/import-manual': {
      id: '/maintenance/import-manual'
      path: '/import-manual'
      fullPath: '/maintenance/import-manual'
      preLoaderRoute: typeof MaintenanceImportManualRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/maintenance/generate-schedule': {
      id: '/maintenance/generate-schedule'
      path: '/generate-schedule'
      fullPath: '/maintenance/generate-schedule'
      preLoaderRoute: typeof MaintenanceGenerateScheduleRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/maintenance/forecast': {
      id: '/maintenance/forecast'
      path: '/forecast'
      fullPath: '/maintenance/forecast'
      preLoaderRoute: typeof MaintenanceForecastRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/maintenance/diagnose': {
      id: '/maintenance/diagnose'
      path: '/diagnose'
      fullPath: '/maintenance/diagnose'
      preLoaderRoute: typeof MaintenanceDiagnoseRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/health/schema': {
      id: '/health/schema'
      path: '/schema'
      fullPath: '/health/schema'
      preLoaderRoute: typeof HealthSchemaRouteImport
      parentRoute: typeof HealthRoute
    }
    '/food/storage': {
      id: '/food/storage'
      path: '/storage'
      fullPath: '/food/storage'
      preLoaderRoute: typeof FoodStorageRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/seasons': {
      id: '/food/seasons'
      path: '/seasons'
      fullPath: '/food/seasons'
      preLoaderRoute: typeof FoodSeasonsRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/reports': {
      id: '/food/reports'
      path: '/reports'
      fullPath: '/food/reports'
      preLoaderRoute: typeof FoodReportsRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/processing': {
      id: '/food/processing'
      path: '/processing'
      fullPath: '/food/processing'
      preLoaderRoute: typeof FoodProcessingRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/prices': {
      id: '/food/prices'
      path: '/prices'
      fullPath: '/food/prices'
      preLoaderRoute: typeof FoodPricesRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/preserve': {
      id: '/food/preserve'
      path: '/preserve'
      fullPath: '/food/preserve'
      preLoaderRoute: typeof FoodPreserveRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/plan': {
      id: '/food/plan'
      path: '/plan'
      fullPath: '/food/plan'
      preLoaderRoute: typeof FoodPlanRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/orchard': {
      id: '/food/orchard'
      path: '/orchard'
      fullPath: '/food/orchard'
      preLoaderRoute: typeof FoodOrchardRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/livestock': {
      id: '/food/livestock'
      path: '/livestock'
      fullPath: '/food/livestock'
      preLoaderRoute: typeof FoodLivestockRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/irrigation': {
      id: '/food/irrigation'
      path: '/irrigation'
      fullPath: '/food/irrigation'
      preLoaderRoute: typeof FoodIrrigationRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/garden': {
      id: '/food/garden'
      path: '/garden'
      fullPath: '/food/garden'
      preLoaderRoute: typeof FoodGardenRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/crops': {
      id: '/food/crops'
      path: '/crops'
      fullPath: '/food/crops'
      preLoaderRoute: typeof FoodCropsRouteImport
      parentRoute: typeof FoodRoute
    }
    '/electrical/standards': {
      id: '/electrical/standards'
      path: '/electrical/standards'
      fullPath: '/electrical/standards'
      preLoaderRoute: typeof ElectricalStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrical/sor': {
      id: '/electrical/sor'
      path: '/electrical/sor'
      fullPath: '/electrical/sor'
      preLoaderRoute: typeof ElectricalSorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrical/qa': {
      id: '/electrical/qa'
      path: '/electrical/qa'
      fullPath: '/electrical/qa'
      preLoaderRoute: typeof ElectricalQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrical/import': {
      id: '/electrical/import'
      path: '/electrical/import'
      fullPath: '/electrical/import'
      preLoaderRoute: typeof ElectricalImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrical/export': {
      id: '/electrical/export'
      path: '/electrical/export'
      fullPath: '/electrical/export'
      preLoaderRoute: typeof ElectricalExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrical/diagrams': {
      id: '/electrical/diagrams'
      path: '/electrical/diagrams'
      fullPath: '/electrical/diagrams'
      preLoaderRoute: typeof ElectricalDiagramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrical/$kind': {
      id: '/electrical/$kind'
      path: '/electrical/$kind'
      fullPath: '/electrical/$kind'
      preLoaderRoute: typeof ElectricalKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vault-secrets': {
      id: '/admin/vault-secrets'
      path: '/admin/vault-secrets'
      fullPath: '/admin/vault-secrets'
      preLoaderRoute: typeof AdminVaultSecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vault-rotation': {
      id: '/admin/vault-rotation'
      path: '/admin/vault-rotation'
      fullPath: '/admin/vault-rotation'
      preLoaderRoute: typeof AdminVaultRotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vault-backup': {
      id: '/admin/vault-backup'
      path: '/admin/vault-backup'
      fullPath: '/admin/vault-backup'
      preLoaderRoute: typeof AdminVaultBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/task-health': {
      id: '/admin/task-health'
      path: '/admin/task-health'
      fullPath: '/admin/task-health'
      preLoaderRoute: typeof AdminTaskHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/task-dedupe': {
      id: '/admin/task-dedupe'
      path: '/admin/task-dedupe'
      fullPath: '/admin/task-dedupe'
      preLoaderRoute: typeof AdminTaskDedupeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schema': {
      id: '/admin/schema'
      path: '/admin/schema'
      fullPath: '/admin/schema'
      preLoaderRoute: typeof AdminSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/restore': {
      id: '/admin/restore'
      path: '/admin/restore'
      fullPath: '/admin/restore'
      preLoaderRoute: typeof AdminRestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset': {
      id: '/admin/reset'
      path: '/admin/reset'
      fullPath: '/admin/reset'
      preLoaderRoute: typeof AdminResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/export-key': {
      id: '/admin/export-key'
      path: '/admin/export-key'
      fullPath: '/admin/export-key'
      preLoaderRoute: typeof AdminExportKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/admin/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-settings': {
      id: '/admin/ai-settings'
      path: '/admin/ai-settings'
      fullPath: '/admin/ai-settings'
      preLoaderRoute: typeof AdminAiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-engines': {
      id: '/admin/ai-engines'
      path: '/admin/ai-engines'
      fullPath: '/admin/ai-engines'
      preLoaderRoute: typeof AdminAiEnginesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/addons': {
      id: '/admin/addons'
      path: '/admin/addons'
      fullPath: '/admin/addons'
      preLoaderRoute: typeof AdminAddonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ready': {
      id: '/api/public/ready'
      path: '/api/public/ready'
      fullPath: '/api/public/ready'
      preLoaderRoute: typeof ApiPublicReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electrical/snapshot': {
      id: '/api/electrical/snapshot'
      path: '/api/electrical/snapshot'
      fullPath: '/api/electrical/snapshot'
      preLoaderRoute: typeof ApiElectricalSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrical/item/$kind/$id': {
      id: '/electrical/item/$kind/$id'
      path: '/electrical/item/$kind/$id'
      fullPath: '/electrical/item/$kind/$id'
      preLoaderRoute: typeof ElectricalItemKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/rachio': {
      id: '/api/public/webhooks/rachio'
      path: '/api/public/webhooks/rachio'
      fullPath: '/api/public/webhooks/rachio'
      preLoaderRoute: typeof ApiPublicWebhooksRachioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/task-health': {
      id: '/api/public/hooks/task-health'
      path: '/api/public/hooks/task-health'
      fullPath: '/api/public/hooks/task-health'
      preLoaderRoute: typeof ApiPublicHooksTaskHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/rachio-sync': {
      id: '/api/public/hooks/rachio-sync'
      path: '/api/public/hooks/rachio-sync'
      fullPath: '/api/public/hooks/rachio-sync'
      preLoaderRoute: typeof ApiPublicHooksRachioSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/procedures': {
      id: '/api/public/health/procedures'
      path: '/procedures'
      fullPath: '/api/public/health/procedures'
      preLoaderRoute: typeof ApiPublicHealthProceduresRouteImport
      parentRoute: typeof ApiPublicHealthRoute
    }
  }
}

interface FoodRouteChildren {
  FoodCropsRoute: typeof FoodCropsRoute
  FoodGardenRoute: typeof FoodGardenRoute
  FoodIrrigationRoute: typeof FoodIrrigationRoute
  FoodLivestockRoute: typeof FoodLivestockRoute
  FoodOrchardRoute: typeof FoodOrchardRoute
  FoodPlanRoute: typeof FoodPlanRoute
  FoodPreserveRoute: typeof FoodPreserveRoute
  FoodPricesRoute: typeof FoodPricesRoute
  FoodProcessingRoute: typeof FoodProcessingRoute
  FoodReportsRoute: typeof FoodReportsRoute
  FoodSeasonsRoute: typeof FoodSeasonsRoute
  FoodStorageRoute: typeof FoodStorageRoute
  FoodIndexRoute: typeof FoodIndexRoute
}

const FoodRouteChildren: FoodRouteChildren = {
  FoodCropsRoute: FoodCropsRoute,
  FoodGardenRoute: FoodGardenRoute,
  FoodIrrigationRoute: FoodIrrigationRoute,
  FoodLivestockRoute: FoodLivestockRoute,
  FoodOrchardRoute: FoodOrchardRoute,
  FoodPlanRoute: FoodPlanRoute,
  FoodPreserveRoute: FoodPreserveRoute,
  FoodPricesRoute: FoodPricesRoute,
  FoodProcessingRoute: FoodProcessingRoute,
  FoodReportsRoute: FoodReportsRoute,
  FoodSeasonsRoute: FoodSeasonsRoute,
  FoodStorageRoute: FoodStorageRoute,
  FoodIndexRoute: FoodIndexRoute,
}

const FoodRouteWithChildren = FoodRoute._addFileChildren(FoodRouteChildren)

interface HealthRouteChildren {
  HealthSchemaRoute: typeof HealthSchemaRoute
}

const HealthRouteChildren: HealthRouteChildren = {
  HealthSchemaRoute: HealthSchemaRoute,
}

const HealthRouteWithChildren =
  HealthRoute._addFileChildren(HealthRouteChildren)

interface MaintenanceRouteChildren {
  MaintenanceDiagnoseRoute: typeof MaintenanceDiagnoseRoute
  MaintenanceForecastRoute: typeof MaintenanceForecastRoute
  MaintenanceGenerateScheduleRoute: typeof MaintenanceGenerateScheduleRoute
  MaintenanceImportManualRoute: typeof MaintenanceImportManualRoute
  MaintenanceIndexRoute: typeof MaintenanceIndexRoute
}

const MaintenanceRouteChildren: MaintenanceRouteChildren = {
  MaintenanceDiagnoseRoute: MaintenanceDiagnoseRoute,
  MaintenanceForecastRoute: MaintenanceForecastRoute,
  MaintenanceGenerateScheduleRoute: MaintenanceGenerateScheduleRoute,
  MaintenanceImportManualRoute: MaintenanceImportManualRoute,
  MaintenanceIndexRoute: MaintenanceIndexRoute,
}

const MaintenanceRouteWithChildren = MaintenanceRoute._addFileChildren(
  MaintenanceRouteChildren,
)

interface ProceduresRouteChildren {
  ProceduresIngestRoute: typeof ProceduresIngestRoute
  ProceduresIndexRoute: typeof ProceduresIndexRoute
}

const ProceduresRouteChildren: ProceduresRouteChildren = {
  ProceduresIngestRoute: ProceduresIngestRoute,
  ProceduresIndexRoute: ProceduresIndexRoute,
}

const ProceduresRouteWithChildren = ProceduresRoute._addFileChildren(
  ProceduresRouteChildren,
)

interface ApiPublicHealthRouteChildren {
  ApiPublicHealthProceduresRoute: typeof ApiPublicHealthProceduresRoute
}

const ApiPublicHealthRouteChildren: ApiPublicHealthRouteChildren = {
  ApiPublicHealthProceduresRoute: ApiPublicHealthProceduresRoute,
}

const ApiPublicHealthRouteWithChildren = ApiPublicHealthRoute._addFileChildren(
  ApiPublicHealthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DeckRoute: DeckRoute,
  FoodRoute: FoodRouteWithChildren,
  HealthRoute: HealthRouteWithChildren,
  InventoryRoute: InventoryRoute,
  MaintenanceRoute: MaintenanceRouteWithChildren,
  ProceduresRoute: ProceduresRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  ReadyRoute: ReadyRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServiceSchedulingRoute: ServiceSchedulingRoute,
  SyncRoute: SyncRoute,
  VaultRoute: VaultRoute,
  AdminAddonsRoute: AdminAddonsRoute,
  AdminAiEnginesRoute: AdminAiEnginesRoute,
  AdminAiSettingsRoute: AdminAiSettingsRoute,
  AdminExportRoute: AdminExportRoute,
  AdminExportKeyRoute: AdminExportKeyRoute,
  AdminResetRoute: AdminResetRoute,
  AdminRestoreRoute: AdminRestoreRoute,
  AdminSchemaRoute: AdminSchemaRoute,
  AdminTaskDedupeRoute: AdminTaskDedupeRoute,
  AdminTaskHealthRoute: AdminTaskHealthRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVaultBackupRoute: AdminVaultBackupRoute,
  AdminVaultRotationRoute: AdminVaultRotationRoute,
  AdminVaultSecretsRoute: AdminVaultSecretsRoute,
  ElectricalKindRoute: ElectricalKindRoute,
  ElectricalDiagramsRoute: ElectricalDiagramsRoute,
  ElectricalExportRoute: ElectricalExportRoute,
  ElectricalImportRoute: ElectricalImportRoute,
  ElectricalQaRoute: ElectricalQaRoute,
  ElectricalSorRoute: ElectricalSorRoute,
  ElectricalStandardsRoute: ElectricalStandardsRoute,
  NotesDateRoute: NotesDateRoute,
  SettingsSelfHostRoute: SettingsSelfHostRoute,
  SettingsTroubleshootingRoute: SettingsTroubleshootingRoute,
  TasksSlugRoute: TasksSlugRoute,
  TasksBacklogRoute: TasksBacklogRoute,
  TasksRefsRoute: TasksRefsRoute,
  TasksScheduledRoute: TasksScheduledRoute,
  AdminIndexRoute: AdminIndexRoute,
  ElectricalIndexRoute: ElectricalIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  ApiElectricalSnapshotRoute: ApiElectricalSnapshotRoute,
  ApiPublicHealthRoute: ApiPublicHealthRouteWithChildren,
  ApiPublicReadyRoute: ApiPublicReadyRoute,
  ApiPublicHooksRachioSyncRoute: ApiPublicHooksRachioSyncRoute,
  ApiPublicHooksTaskHealthRoute: ApiPublicHooksTaskHealthRoute,
  ApiPublicWebhooksRachioRoute: ApiPublicWebhooksRachioRoute,
  ElectricalItemKindIdRoute: ElectricalItemKindIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
